### ISSUE TITLE
The logo is missing

### ISSUE THREAD

**Issue by AniteiAlina** [peviitor-ro/Scrapers_Cristi_Olteanu#1]
STEPS TO REPRODUCE:

Open "https://scrapers.peviitor.ro/".
Type “Adecco” on the search bar.
Click on “Adecco”
Check the logo

EXPECTED RESULTS:
See the Adecco logo

ACTUAL RESULT:
The Adecco logo does not appear

<img width="1063" alt="Screenshot at Oct 18 13-56-15" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/131695035/6af7a4af-5919-4363-a18b-cb295092d7fa">

**Comment by lalalaurentiu** [comment]
Fixed!
