### ISSUE TITLE
The number of jobs on Dennemeyer does not correspond to the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#10]
ENVIROMENT: production
COMPANY: Dennemeyer.
URL: [Dennemeyer peviitor.ro](https://peviitor.ro/rezultate?q=dennemeyer&country=Rom%C3%A2nia&page=1)
Company's Career website: [Dennemeyer official website](https://dennemeyer.wd3.myworkdayjobs.com/dennemeyer_careers?locations=99c9060b642e1001e86635de40a00000)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:

Enter Dennemeyer in the search bar.

Click the button the company logo.

Expected results:

The number of jobs on [pe.viitor.ro](http://www.peviitor.ro/) corresponds to the number of jobs on [Dennemeyer](https://dennemeyer.wd3.myworkdayjobs.com/dennemeyer_careers?locations=99c9060b642e1001e86635de40a00000) official website

Actual result:

The number of jobs on [pe.viitor.ro](http://www.peviitor.ro/) do not correspond to the number of jobs on [Dennemeyer](https://dennemeyer.wd3.myworkdayjobs.com/dennemeyer_careers?locations=99c9060b642e1001e86635de40a00000) official website
<img width="855" alt="bugde" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/21209eee-4741-4f04-9962-278d1d267de2">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/33d8f444-e424-4030-81c7-f90a6d88e848)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/0d2e348e-af21-4ee6-b110-0fe887b6453f)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/11d90898-78a0-4650-a2ca-dc0a5b4f483c)
