### ISSUE TITLE
Signanthealth - Job types do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#102]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Signanthealth](https://globalus232.dayforcehcm.com/CandidatePortal/en-US/signanthealth?l=3)
 Desktop:
```
OS: IOS
Browser: Safari, Chrome
Version: 14.2.1, 120.0.6099.199
```

 
### **STEPS TO REPRODUCE:**

1) **Write** "Signanthealth" in the search bar
2) **Click** on the company folder 
3) **Observe** the job types for the job listings
4) **Navigate** to and **click** on the "Careers" button on the logo box
5) **Observe** and **compare** the official website with the scrapers page job types

>**EXPECTED RESULTS:**
The job types should accurately reflect the information provided by the official website.

>**ACTUAL RESULTS:**
Differences are observed in job types.
<br>

**Screenshots**
<img width="1150" alt="Screenshot 2024-01-12 at 21 37 48" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/10a1be14-c091-4945-b3fb-ab45286b77b1">

<img width="668" alt="Screenshot 2024-01-12 at 21 25 14" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/a0985b7b-508f-4630-84ea-79287369f79b">

<img width="671" alt="Screenshot 2024-01-12 at 21 25 04" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/b7edb8e6-fa81-442a-8e78-00d623fd111f">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/9c9eebe9-cde9-4ccf-88bd-eaab0d7dd939)

**Comment by iBixee** [comment]
Looks good. Thank you!
