### ISSUE TITLE
AMS - Job type is missing

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#103]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/ams/index.html)
**Company_careers_url**: [AMS](https://www.careers-page.com/ams-hr/job/QV7348W8)
 Desktop:
```
OS: IOS
Browser: Google Chrome
Version: 98.0.4758.102
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter AMS in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
Some jobs have job type displayed

>**ACTUAL RESULTS:**
There are jobs that lack the job type

<br>

**Screenshots**
<img width="988" alt="Screenshot at Jan 15 13-41-34" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/725f0e78-4765-4440-ab43-360142848237">
<img width="522" alt="Screenshot at Jan 15 13-42-27" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/a5911f6b-1935-4204-8c2b-7e764e697609">
<img width="512" alt="Screenshot at Jan 15 13-51-06" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/7045381b-19b9-49ad-b95c-177399752ff7">
<img width="505" alt="Screenshot at Jan 15 13-51-23" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/37f1e65a-c6cf-4614-820d-471f1fd2b1c4">
<img width="484" alt="Screenshot at Jan 15 13-51-43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/900f0dce-29ca-4d99-bddd-e12d97c67d3f">
<img width="482" alt="Screenshot at Jan 15 13-52-01" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/c486550b-a30d-4f4e-abf8-13d7eb37935f">
<img width="581" alt="Screenshot at Jan 15 13-52-31" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/62667283-9563-44ba-975a-187d4b3f1bee">
<img width="537" alt="Screenshot at Jan 15 13-52-50" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/25dcc8af-51e8-44a3-836d-fcb42c18f4e7">
<img width="532" alt="Screenshot at Jan 15 13-53-09" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/93508c8b-58e0-4e1c-969c-bde063dc72c5">

**Comment by cristiol** [comment]
fixed

![Uploading image.png…]()
