### ISSUE TITLE
Astormueller - The number of jobs does not correspond with the number of jobs from the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#104]
ENVIROMENT: production
URL: [Astormueller scrapers.peviitor](https://scrapers.peviitor.ro/src/astormueller/index.html)
**Company_careers_url**: [Astormueller](https://astormueller-ag.jobs.personio.com/?filters=eyJvZmZpY2VfaWQiOlsxMTEzNzYzLDE3NDAyMDJdfQ==)
 Desktop:
```
OS: IOS
Browser: Chrome
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Astormueller in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/astormueller/index.html) corresponds to the number of jobs from the [Astormueller](https://astormueller-ag.jobs.personio.com/?filters=eyJvZmZpY2VfaWQiOlsxMTEzNzYzLDE3NDAyMDJdfQ==) official website

>**ACTUAL RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/astormueller/index.html) does not correspond to the number of jobs from the [Astormueller](https://astormueller-ag.jobs.personio.com/?filters=eyJvZmZpY2VfaWQiOlsxMTEzNzYzLDE3NDAyMDJdfQ==) official website

<br>

**Screenshots**
<img width="418" alt="Screenshot at Jan 17 13-38-43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/f7342974-5785-41d7-ae09-0fcf3b775d11">
<img width="531" alt="Screenshot at Jan 17 13-38-59" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/494400ba-49dc-4f2c-ac7c-9f421f3f7252">

**Comment by cristiol** [comment]
2 jobs are Germany remote
