### ISSUE TITLE
Siena - Location not recognised as city in Romania

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#105]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Company's _name_](https://jobs.ashbyhq.com/siena)
 Desktop:
```
OS: IOS
Browser: Safari, Chrome
Version: 17.2.1, 120.0.6099.234
```

 
### **STEPS TO REPRODUCE:**
1) Write **Siena** in the search bar
2) **Click** on the company folder
3) **Click** on the Run Scraper button
4) **Observe** the job locations for the job listings

>**EXPECTED RESULTS:**
Locations should be listed correctly in the location container.

>**ACTUAL RESULTS:**
Cluj Napoca is listed as not being a city in Romania

<br>

**Screenshots**
<img width="800" alt="Screenshot 2024-01-24 at 18 30 29" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/52d3c3cd-9632-493b-b3b3-79a8fbaff3cc">

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/d93a4af4-209f-4c27-aded-43d0f60f8614)

**Comment by iBixee** [comment]
Thank you!
