### ISSUE TITLE
Shutterstock - External job location listed as job type on page

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#106]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Shutterstock](https://careers.shutterstock.com/us/en/search-results%20%20%20%20%20%20%20%20%20%20%20%20%20%20#)
 Desktop:
```
OS: IOS
Browser: Safari, Chrome
Version: 17.2.1, 120.0.6099.234
```

 
### **STEPS TO REPRODUCE:**
1) **Write** "Shutterstock" in the search bar
2) **Click** on the company folder
3) **Click** on the "Run Scraper" button
4) **Observe** job type
5) **Click** on the "Vezi Postul" button
6) **Observe** the job type on the official page

>**EXPECTED RESULTS:**
Job type should be listed as on-site, hybrid or remote

>**ACTUAL RESULTS:**
One of the job locations is listed in the job type field and it is not a location in Romania.
<br>

**Screenshots**
...
<img width="652" alt="Screenshot 2024-01-24 at 19 11 09" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/64c93608-88ac-41fc-b3a1-8cacdc97546e">

<img width="668" alt="Screenshot 2024-01-24 at 19 10 43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/c71d6174-0a27-4a40-9b5c-4fcfd21bbef9">

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/e2ed8c9b-9ffe-4317-b217-af7ee76ae392)

**Comment by iBixee** [comment]
Thank you!
