### ISSUE TITLE
Sennder - Job title and job location issues

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#107]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Sennder](https://www.sennder.com/open-positions)
 Desktop:
```
OS: IOS
Browser: Safari, Chrome
Version: 17.2.1, 120.0.6099.234
```

 
### **STEPS TO REPRODUCE:**
1) Write "Sennder" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Observe the job titles
5) Observe the job locations

>**EXPECTED RESULTS:**
Job titles and locations should be listed in different locations on the page and accurately reflect the data on the official webpage.

>**ACTUAL RESULTS:**
Job titles are listed along with the locations.
Job locations are not recognised as cities in Romania.
There are spaces missing between some words.

 <br>

**Screenshots**
...
<img width="732" alt="Screenshot 2024-01-24 at 19 32 13" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/86f7e3b2-bf0d-474f-89e5-6a95907b0644">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/3c7bfa72-9681-458b-aa64-591b982d6bb6)

**Comment by iBixee** [comment]
Thank you!
