### ISSUE TITLE
Grubhub - Database load failed

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#108]
ENVIROMENT: production
COMPANY: Grubhub
URL: [Grubhub scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/grubhub/index.html)
Browser: Firefox
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Firefox browser.

Steps:
1. Click on Firme from footer.
2. Enter Grubhub in the search bar.
3. Click the button under the company's logo.
4. Click the button "Run Scraper".

Expected result:
The scraper is updating

Actual result:
Load failed.
<img width="984" alt="Screenshot at Jan 24 15-15-38" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/9ddf4825-0f87-488a-835e-525d26c88a9a">

**Comment by lalalaurentiu** [comment]
@cristiol scraperul nu mai functioneaza din data de 18
<img width="1440" alt="Screenshot 2024-01-26 at 23 57 20" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/67306273/8c1d61f6-f9dc-4c1f-8bc0-c61d8cb9fb0d">

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/58ddf7c4-d32f-4cdc-997d-be931fc99912)
