### ISSUE TITLE
The numbers of jobs from Ecolab does not correspond with the official site

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#11]
ENVIROMENT: production
COMPANY: Ecolab
URL: [Ecolab peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1)
Company's Career website: [Ecolab official website](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:

1. Enter Ecolab in the search bar.
2. Click the company logo.

Expected results:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1) corresponds to the number of jobs on [Ecolab](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25) official website

Actual result:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1) do not correspond to the number of jobs on [Ecolab](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25) official website
<img width="1415" alt="bug eco" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/a44fa584-f200-4500-95e3-d286114c5d55">
<img width="1254" alt="bug eco3" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/78b8479c-6e34-4abb-bc76-2a5d3b163721">

**Comment by cristiol** [comment]
same issue as this one, and I already responded.
https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/issues/8
