### ISSUE TITLE
Hitachienergy - The number of jobs does not correspond with the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#110]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/hitachienergy/index.html)
**Company_careers_url**: [Hitachienergy](https://www.hitachienergy.com/careers/open-jobs?filterable1573558966-location=Romania%2FBucharest+New%2CRomania%2FBucharest++Ilfov&filterable0-location=Romania%2FBucharest++Ilfov&filterable0-offset=0&filterable0-calculatedOffset=0)
 Desktop:
```
OS: IOS
Browser: Chrome
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Hitachienergy in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/hitachienergy/index.html) corresponds to the number of jobs from the [Hitachienergy](https://www.hitachienergy.com/careers/open-jobs?filterable1573558966-location=Romania%2FBucharest+New%2CRomania%2FBucharest++Ilfov&filterable0-location=Romania%2FBucharest++Ilfov&filterable0-offset=0&filterable0-calculatedOffset=0) official website

>**ACTUAL RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/hitachienergy/index.html) does not correspond to the number of jobs from the [Hitachienergy](https://www.hitachienergy.com/careers/open-jobs?filterable1573558966-location=Romania%2FBucharest+New%2CRomania%2FBucharest++Ilfov&filterable0-location=Romania%2FBucharest++Ilfov&filterable0-offset=0&filterable0-calculatedOffset=0) official website

<br>

**Screenshots**
<img width="1318" alt="Screenshot at Jan 31 16-40-41" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/5c80bbc4-1125-494e-9984-4b87ffb908e2">
<img width="413" alt="Screenshot at Jan 31 16-40-51" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/44457a17-2d7e-4381-8161-162ab3e820d0">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/1bbe14cc-e9ac-4043-aef8-41d38573b8a2)
