### ISSUE TITLE
RedBull - Job title issues

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#112]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Company_careers_url: [RedBull](https://jobs.redbull.com/ro-ro/results?locations=6188&locationNames=România&functions=&functionNames=&keywords=)
Device: Laptop
OS: Sonoma 14.2.1
Browser: Safari, Chrome
Version: 17.2.1, 121.0.6167.139

STEPS TO REPRODUCE:

1) Write "RedBull" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Observe the job titles

EXPECTED RESULTS:
Job titles and locations should be listed in different locations on the page

ACTUAL RESULTS:
Job titles are listed along with the locations.

Screenshots
<img width="848" alt="Screenshot 2024-02-01 at 09 46 43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/ae6c7c7b-6918-4bf0-bc6b-30271344614d">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/715cf824-6a54-4835-adea-5c03bd0dea05)

**Comment by iBixee** [comment]
Looking good now! Thank you!
