### ISSUE TITLE
Pepsico - Location data issues for some of the job listings

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#113]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Pepsico](https://www.pepsicojobs.com/main/jobs?stretchUnits=MILES&stretch=10&location=Romania&lat=46&lng=25&woe=12&page=2&country=Romania)
Device: Laptop
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1

 
### **STEPS TO REPRODUCE:**
1) Write "Pepsico" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job titles

>**EXPECTED RESULTS:**
Job locations should reflect data on the company's official website.

>**ACTUAL RESULTS:**
Some job locations are written incorrectly.
<br>

**Screenshots**
<img width="953" alt="Screenshot 2024-02-01 at 10 18 56" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/7a46a47a-94ca-4427-8ff8-68164e4ffc2b">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/703ebd35-bf13-4882-ba07-b7cd738d45a4)

**Comment by iBixee** [comment]
Istanbul trying to occupy Romania :))

<img width="705" alt="Screenshot 2024-02-01 at 19 10 33" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/11fb8a31-42db-4b53-93e7-37e908539608">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/32c1da2b-04d8-4bbd-a451-40fa065fb2d9)

**Comment by iBixee** [comment]
Looks good now! Thank you!
