### ISSUE TITLE
Mobilexpense - Cluj not recognised as a city in Romania

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#114]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Mobilexpense](https://mobilexpense.recruitee.com)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**

1) Type "Mobilexpense" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job locations

>**EXPECTED RESULTS:**
Job locations should be listed correctly in the job listing container.

>**ACTUAL RESULTS:**
Some of the job locations are listed as "Cluj is not a city in Romania".

<br>

**Screenshots**
...
<img width="1048" alt="Screenshot 2024-02-09 at 18 35 00" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e61efdf5-13f7-459f-8074-e1c19d0d3fa8">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/8eacb921-a469-48ec-90a5-b680a4548570)

**Comment by iBixee** [comment]
Thank you!
