### ISSUE TITLE
Mambu - Incorrect location found in one of the job listings

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#116]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Mambu](https://careers-mambu.icims.com/jobs/search?ss=1&searchLocation=13526--)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**
1) Type "Mambu" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job locations

>**EXPECTED RESULTS:**
Job locations are listed correctly in the job listing container.

>**ACTUAL RESULTS:**
Job location is listed as "Amsterdam is not a city in Romania".

<br>

**Screenshots**
...
<img width="912" alt="Screenshot 2024-02-09 at 19 44 37" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/392c2358-6b76-4af5-b361-9a8f4ad15ce1">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/74744f5f-3721-4e84-a400-0fe74142af3a)

**Comment by iBixee** [comment]
Looks good! Thank you!
