### ISSUE TITLE
Lectra - Cluj not recognised as a city in Romania

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#119]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Lectra](https://careers.lectra.com/search/?q=&q2=&alertId=&title=&location=RO&date=)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**
1) Type "Lectra" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job locations

>**EXPECTED RESULTS:**
Job locations are listed correctly in the job listing container.

>**ACTUAL RESULTS:**
Job location is listed as "Cluj is not a city in Romania".

<br>

**Screenshots**
...
<img width="745" alt="Screenshot 2024-02-09 at 21 17 04" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/0d0fb4ff-25b5-4dab-b47e-99154db21764">

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/d12324af-415c-455c-89ba-c5a4e327e461)

**Comment by iBixee** [comment]
Looks good now! Thank you!

<img width="909" alt="Screenshot 2024-02-09 at 21 45 39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/2862d571-ca0f-4149-b9d8-e77269100331">
