### ISSUE TITLE
The numbers of jobs from Ecolab does not correspond 

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#12]
ENVIROMENT: production
COMPANY: Ecolab
URL: [Ecolab peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1)
Company's Career website: [Ecolab official website](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:

1. Enter Ecolab in the search bar.
2. Click the company logo.
3. Click the button Firme from the footer.
4. Enter Ecolab in the search bar.
5. Click the button under the logo company.
6. Click the Run Scraper button.
Expected results:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1) corresponds to the number of jobs on [Ecolab](https://scrapers.peviitor.ro/src/ecolab/) 

Actual result:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1) do not correspond to the number of jobs on [Ecolab](https://scrapers.peviitor.ro/src/ecolab/)
<img width="1415" alt="bug eco" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/4da79b1f-2f2e-4e34-803d-06b69cbad78b">
<img width="950" alt="bug eco2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/50b3c57e-b67e-4e99-a738-7060ed490f58">

**Comment by cristiol** [comment]
not a bug: one of those five jobs is actually from another company
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/dfd5a341-c585-412a-8800-ed270c7b5ac5)
