### ISSUE TITLE
ModusCreate - Several job listing duplicates 

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#122]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [ModusCreate](https://moduscreate.com/careers/?gh_src=504950c63us)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**
1) Type "ModusCreate" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job listings

>**EXPECTED RESULTS:**
Each job opening is posted once.

>**ACTUAL RESULTS:**
Several jobs are listed multiple times.
<br>

**Screenshots**
...
<img width="967" alt="Screenshot 2024-02-09 at 23 22 51" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/ec6f19ba-043c-46d6-baae-8ed699842ea7">

<img width="1159" alt="Screenshot 2024-02-09 at 23 05 54" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/925cbad9-eea8-44e0-a223-09d82dff377d">

<img width="1165" alt="Screenshot 2024-02-09 at 23 08 21" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/a68ab59c-9dce-4ab8-8e40-36a02ac2c1fa">

<img width="1165" alt="Screenshot 2024-02-09 at 23 08 40" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/4d0f54d8-6ea5-4c1f-b003-5037e22d6915">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/b34b7c6b-71dd-4fbb-bc4f-8f4819af8f8b)

**Comment by iBixee** [comment]
Thank you!
