### ISSUE TITLE
Fotc - Job type found in the job title

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#123]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Fotc](https://fotc.jobsoid.com)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**
1) Type "Fotc" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job titles

>**EXPECTED RESULTS:**
Job titles are correctly written in the job details container.

>**ACTUAL RESULTS:**
Job type is listed in the job titles as well.

<br>

**Screenshots**
...
<img width="694" alt="Screenshot 2024-02-09 at 23 41 52" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/1b56c0a0-5234-42fe-9d01-d2dced807a75">

<img width="846" alt="Screenshot 2024-02-09 at 23 42 39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/72b2b5c0-31f0-49fe-9c3d-c4eeb61af1bd">

**Comment by cristiol** [comment]
titlul este preluat exact asa cum este si pe site ul oficial
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/2ef96855-0c59-4b55-8c84-b540334b338d)

**Comment by iBixee** [comment]
Case closed!
