### ISSUE TITLE
ExpressVPN - Number of jobs does not match the official website 

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#124]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [ExpressVPN](https://www.expressvpn.com/jobs/job-openings)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**
1) Type "ExpressVPN" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Observe the job number

>**EXPECTED RESULTS:**
Job listing number matches the official website.

>**ACTUAL RESULTS:**
Discrepancies are observed between job listing number and the data provided on the official website.
Number of job openings on the official website is wrong. 
*There are 14 job openings listed on the official website but 2 of them are located in other countries than Romania.
<br>

**Screenshots**
...
<img width="768" alt="Screenshot 2024-02-10 at 00 06 39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/13af6396-04c8-43d2-b8e1-16feb25e3d16">

<img width="730" alt="Screenshot 2024-02-10 at 00 22 04" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/cf37a788-4644-43b0-8e25-a8dab7929604">

<img width="723" alt="Screenshot 2024-02-10 at 00 09 09" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/297d6e94-76ac-43a5-9269-8b7c9ed25698">

<img width="626" alt="Screenshot 2024-02-10 at 00 09 44" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/3308c12e-45a5-419f-8072-fdb8eeeffe79">

**Comment by cristiol** [comment]
16 joburi sunt 15 Bucuresti plus unul cu Romania la locatie
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/4414c055-bb2c-4f8c-abb8-4cbdd48ea22c)

pe site ul acesta si in general pe site urile ce au domeniul greenhouse nu functioneaza bine filtrele

**Comment by iBixee** [comment]
Got it! Thank you!
