### ISSUE TITLE
Edurom - Number of jobs does not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#125]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Edurom](https://www.edurom.ro/it-jobs/)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**
1) Type "Edurom" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Observe the job number
5) Navigate up and click the "Careers" button
6) Observe job listings on the official website

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
Discrepancies are observed between job listing number and the data provided on the official website.

<br>

**Screenshots**
...
<img width="788" alt="Screenshot 2024-02-10 at 00 41 10" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/39913e6d-5b83-41b7-a915-9c5cfecff945">

https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/30865344-8565-4735-991d-daaf0c442aae

**Comment by cristiol** [comment]
27 de joburi sunt 
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/a5f984d8-6378-49e6-8481-4979e2c34081)
celelalte sunt closed

**Comment by iBixee** [comment]
Sorry about that! Thanks!
