### ISSUE TITLE
Hkr - Locations of the jobs does not correspond with the locations from the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#126]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/hkr/index.html)
**Company_careers_url**: [Hkr](https://jobs.eu.lever.co/hkr/?location=Romania)
 Desktop:
```
OS: IOS
Browser: Mozilla Firefox
```

 
### **STEPS TO REPRODUCE:**
1) Click on "Run Scraper" button
2) Click "Careers" from the company's logo.

>**EXPECTED RESULTS:**
The location of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/hkr/index.html) corresponds to the locations of jobs from the [Hkr](https://jobs.eu.lever.co/hkr/?location=Romania) official website

>**ACTUAL RESULTS:**
The location of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/hkr/index.html) does not correspond to the locations of jobs from the [Hkr](https://jobs.eu.lever.co/hkr/?location=Romania) official website

<br>

**Screenshots**
<img width="962" alt="Screenshot at Feb 13 13-58-39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/97d41090-b39e-4527-a705-c6de1d913bb9">

<img width="534" alt="Screenshot at Feb 13 13-57-33" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/e785b17f-0d4b-4108-be7a-6c5d3bfd7178">

**Comment by cristiol** [comment]
It's not a bug.
When the location is specified as 'Remote Romania' and no city is mentioned, it is agreed that the city will be the one where the company has its registered office.
