### ISSUE TITLE
Edenred - Job types do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#129]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Edenred](https://www.edenred.ro/ro/descopera-jobul-potrivit)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**
1) Write "Edenred" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job types for the job listings
5) Navigate to and click on the "Careers" button on the logo box
6) Observe and compare the official website with the scrapers page job types

>**EXPECTED RESULTS:**
The job types should accurately reflect the information provided by the official website.

>**ACTUAL RESULTS:**
Job types are listed as "No job type".
<br>

**Screenshots**
...
<img width="936" alt="Screenshot 2024-02-13 at 17 48 24" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/9adf3ecc-9e7b-4b4b-a38c-3f5f403bf68d">

<img width="1212" alt="Screenshot 2024-02-13 at 17 41 15" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/84ebffdb-f701-4eb3-a3ad-3b8b11365e0b">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/e1b333a2-e9bf-4061-9bed-a71f8bcec1be)

**Comment by iBixee** [comment]
Looks good! Thank you!
