### ISSUE TITLE
Damen - Status "Inactive"

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#131]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
**Company_careers_url**: [Damen](https://jobs.damen.com/jobs/?customField1=Romania&date=all&keywords=&sort=recent)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**

1) Type "Damen" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Check the "Status" section

>**EXPECTED RESULTS:**
The scraper runs correctly and the message "Active" is displayed in the "Status" section

>**ACTUAL RESULTS:**
The "Inactive" message is displayed in the "Status" section

<br>

**Screenshots**
...
<img width="1205" alt="Screenshot 2024-02-13 at 18 21 02" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/0420c026-bde7-4b13-abbc-d19c6b18e275">

**Comment by cristiol** [comment]
This scraper will be deprecated because the API response's status code is 405.

I put the scraper in the exclude folder, so it will not be run anymore.

**Comment by iBixee** [comment]
Good to know. Thank you!
