### ISSUE TITLE
Conduent - Job type and location found in the job title

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#132]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: [Conduent](https://careers.conduent.com/us/en/search-results)
 Device: Laptop
```
OS: Sonoma 14.2.1
Browser: Safari
Version: 17.2.1
```

 
### **STEPS TO REPRODUCE:**

1) Type "Conduent" in the search bar
2) Click on the company folder
3) Click on the "Run Scraper" button
4) Scroll down and observe the job titles

>**EXPECTED RESULTS:**
Job titles are correctly written in the job details container.

>**ACTUAL RESULTS:**
Job type and location is listed in the job title as well.

<br>

**Screenshots**
...
<img width="1199" alt="Screenshot 2024-02-13 at 19 22 38" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/d396ac54-c83a-4afb-ac12-1abcbb1da2a8">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/4ee070a9-9fc4-4a35-ba1a-9607ea37c8a4)

**Comment by iBixee** [comment]
Thank you!
