### ISSUE TITLE
Jobs number on peViitor.ro not match with the Scraper listed jobs

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#133]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: https://careers.stryker.com/job-search-results/?location=Romania&country=RO&radius=25
 Desktop: PC DESKTOP
```
OS: Windows 11 Home , 64 bit 
Browser: Google Chrome 
Version:  121.0.6167.161
```

 
### **STEPS TO REPRODUCE:**
1) Type "Stryker" in the search bar
2) Click on the company folder.
3)Click on the "Run Scraper" button.
4)Scroll and see the jobs under and  the job titles.

>**EXPECTED RESULTS:**
Found 5 jobs with description on the peviitor.ro

>**ACTUAL RESULTS:**
There is 8 jobs displayed on peviitor.ro instead of 5.
**Screenshots**
![Screenshot 2024-02-13 194726](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/83bc3d60-5ced-4b14-80d2-5e09f992bf92)
![Screenshot 2024-02-13 194833](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/bada2993-066e-4377-b1e9-64cf46c9e068)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/d5f5f90c-1560-474c-98d9-a9bad489edab)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/89d53ba9-f713-4526-9d7f-a7ea07462323)
