### ISSUE TITLE
Different number of jobs on Snyk that on peviitor.ro

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#137]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: https://boards.greenhouse.io/snyk?gh_src=3f9b65652us
![Screenshot 2024-02-17 101543](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/3a4d4e36-f26d-45e7-ba36-37ca8151a91f)
![Screenshot 2024-02-17 101618](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/8538d8df-ad78-471d-ab26-15c40b9651a4)
![Screenshot 2024-02-17 101642](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/9a2af198-de02-4b12-9feb-886b73d3bb8a)

 Desktop: Pc Desktop
```
OS: Windows 11 Home 64 bit
Browser: Google Chrome
Version:  121.0.6167.185
```

 
### **STEPS TO REPRODUCE:**
1) Open scraper page in browser.
2) Click on carrer Snyk.

>**EXPECTED RESULTS:**
Number of jobs to corespund with the scraper career job page.

>**ACTUAL RESULTS:**
Number of jobs different that diplsyed on peviitor.ro
<br>

**Screenshots**
...

**Comment by cristiol** [comment]
This is not a bug; greenhouse sites have a problem with filtering, so the accurate method to count the number is using ctrl+f + 'city name'.

In this case, there are 19 jobs, so it's not a bug.
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/8b60ae1a-e784-49ba-b062-4dea1e47e814)


In this example, the filter shows 18 jobs, but if you use ctrl+f, you find out that on the page are actually listed 16.
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/8076ab2c-c3d6-46d4-9f36-6d8a201ac70c)
