### ISSUE TITLE
Jobs Signanthealth Hiperlink redirect wit a page with 301 redirect 

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#138]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: https://globalus232.dayforcehcm.com/CandidatePortal/en-US/signanthealth?l=3
 Desktop: Pc Desktop
```
OS: Windows 11 Home 64 bit
Browser: Google Chrome 
Version: 121.0.6167.185
```

 
### **STEPS TO REPRODUCE:**
1) Open URL Scrapers.peviitor.ro in the browser.
2) Click on Run scraper button.
3) Scrol down of the page.
4) Click on the hiperlink job "Financial Planning & Analysis Manager - Finance" and "Financial Planning & Analysis Manager - Finance"

>**EXPECTED RESULTS:**
Links should redirect to job page and display correct data.
>**ACTUAL RESULTS:**
Display Error redirect page 301.
![Screenshot 2024-02-17 103741](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/6e3c5600-bb93-4bdb-b9fe-0b574e78354a)
![Screenshot 2024-02-17 103756](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/8e07592f-c2f9-43cc-b7e5-c66c41219a65)
![Screenshot 2024-02-17 103817](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/3833da5f-89cd-4e41-9a0c-590caf7d9fbe)

<br>

**Screenshots**
...

**Comment by cristiol** [comment]
It seems right to me. Every link works; please retest and close the issue
