### ISSUE TITLE
The number of jobs from Edurom does not correspond with the official site

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#14]
ENVIROMENT: production
COMPANY: Edurom.
URL: [Edurom peviitor.ro](https://peviitor.ro/rezultate?q=Edurom&country=Rom%C3%A2nia&page=9)
Company's Career website: [Edurom official website](https://www.edurom.ro/it-jobs/?job__status_spec=open)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:

Enter Edurom in the search bar.

Click the button the company logo.

Expected results:

The number of jobs on [pe.viitor.ro](https://peviitor.ro/rezultate?q=Edurom&country=Rom%C3%A2nia&page=9) corresponds to the number of jobs on [Edurom](https://www.edurom.ro/it-jobs/?job__status_spec=open) official website

Actual result:

The number of jobs on [pe.viitor.ro](https://peviitor.ro/rezultate?q=Edurom&country=Rom%C3%A2nia&page=9) do not correspond to the number of jobs on [Edurom](https://www.edurom.ro/it-jobs/?job__status_spec=open) official website

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/1945bca3-2373-40cb-aca4-f5a7c00de5c6)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/a49d3e73-49a1-423e-adc8-e329d43a7337)
