### ISSUE TITLE
Ruse is not a city in România for the scraper Salesconsulting

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#141]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/salesconsulting/index.html
Browser: Chrome
Device: Pc Desktop
OS: Windows 11 Home

STEPS TO REPRODUCE:

1.Open URL in browser
2.Click on 'Run Scraper' button
3.Check for "Plant Manager".

EXPECTED RESULTS:
City need to be found in Romania.

ACTUAL RESULTS:
Ruse is a City  in Bulgaria.

![Screenshot 2024-02-17 121603](https://github.com/peviitor-ro/Scrapers-UI/assets/128740240/4c3b904e-60ca-435c-bb81-07fe3fbd84ea)

**Comment by cristiol** [comment]
fixed
