### ISSUE TITLE
Riverbed - Status INACTIV

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#142]
ENVIROMENT: production
COMPANY: Riverbed
URL: [Riverbed peviitor.ro](https://scrapers.peviitor.ro/src/riverbed/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/rian-partners/index.html) must be open in browser.

Steps:
1. Click the Run Scraper button.

Expected result:
The the company's database is updated.

Actual result:
Status INACTIV
<img width="960" alt="Screenshot at Feb 16 16-26-12" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/d6a103a2-42a9-453f-8f30-bd51f177d4ac">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/fce6ad83-f242-4fed-86ab-3e27f5e91c5b)
