### ISSUE TITLE
Siena logo is missing

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#143]
ENVIROMENT: production
COMPANY: Siena
URL: https://firme.peviitor.ro/
Browser: Google Chrome
Device: PC Desktop
OS: windows 11 Home 64 bit 

Precondition:

Site https://firme.peviitor.ro/ need to be open in browser.

Steps:

 In the search bar type Siena.

![Screenshot 2024-02-17 112646](https://github.com/peviitor-ro/Scrapers-UI/assets/128740240/98febbeb-50b0-4a13-b4b8-d660f8556863)

 
Expected result:

Logo is diplayed.

Actual result:
The company logo is missing.

**Comment by lalalaurentiu** [comment]
@cristiol schimba url-ul logoului, din scraper, cu "https://app.ashbyhq.com/api/images/org-theme-wordm…757542ee/e92203a5-67f3-4e3c-bd29-c43e5003276e.png". Cel din scraper este not found

**Comment by OctavianGriga** [comment]
Primesc eroare la 
"[https://app.ashbyhq.com/api/images/org-theme-wordm…757542ee/e92203a5-67f3-4e3c-bd29-c43e5003276e.png](https://app.ashbyhq.com/api/images/org-theme-wordm%E2%80%A6757542ee/e92203a5-67f3-4e3c-bd29-c43e5003276e.png)"
