### ISSUE TITLE
Awin - The number of jobs does not correspond with the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#145]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/awin/index.html)
**Company_careers_url**: [Awin](https://boards.greenhouse.io/awin)
 Device: iPad Mini
```
OS: IOS
Browser: Chrome
```

 
### **STEPS TO REPRODUCE:**
1) Click on "Run Scraper" button
2) Click "Careers" from the company's logo.

>**EXPECTED RESULTS:**
The location of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/awin/index.html) corresponds to the locations of jobs from the [Awin](https://boards.greenhouse.io/awin) official website

>**ACTUAL RESULTS:**
The location of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/awin/index.html) does not correspond to the locations of jobs from the [Awin](https://boards.greenhouse.io/awin) official website

<br>

**Screenshots**
<img width="475" alt="Screenshot at Feb 26 13-07-16" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/1fe7ac10-c3a0-433e-9748-4c993278a77e">
<img width="200" alt="Screenshot at Feb 26 13-07-30" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/3c46b14a-a590-4a7f-aac7-5a4f50b91f7e">

**Comment by cristiol** [comment]
there are 18 jobs on peviitor
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/e59bdea7-c17a-465e-86e7-48ddf1f497e6)
18 on company s site
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/7bc5c819-6041-430f-83d4-7d354ce9ecbe)
