### ISSUE TITLE
 Fltechnics - The numbers of jobs does not correspond

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#146]
ENVIROMENT: production
COMPANY: Fltechnics
URL 1: [Fltechnics peviitor.ro](https://scrapers.peviitor.ro/src/fltechnics/index.html)
URL 2: [Fltechnics peviitor.ro](https://peviitor.ro/rezultate?q=Fltechnics&company=fltechnics&country=România&page=1)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Fltechnics in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.
Click the See jobs button.

Expected result:
The number of jobs on [Scraper Ui](https://scrapers.peviitor.ro/src/fltechnics/index.html) coincides with the jobs on the presentation [site](https://peviitor.ro/rezultate?q=Fltechnics&company=fltechnics&country=România&page=1)

Actual result:
The number of jobs on [Scraper Ui](https://scrapers.peviitor.ro/src/fltechnics/index.html) does not coincide with the jobs on the presentation [site](https://peviitor.ro/rezultate?q=Fltechnics&company=fltechnics&country=România&page=1)

<img width="484" alt="Screenshot at Feb 27 14-37-31" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/8a34f794-d14c-4fd4-86aa-3784dc13e495">
<img width="322" alt="Screenshot at Feb 27 14-37-45" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/42db88c3-e724-4167-bad3-cb9cfb438db5">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/ecf0cbd0-cd52-4cf7-a698-3c75415d54bf)
