### ISSUE TITLE
Adecco - Invalid city names

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#147]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/adecco/index.html)
**Company_careers_url**: [Adecco](https://www.adecco.ro/jobs/?page=0)
 Desktop:
```
OS: MacOS
Browser: Safari
```
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Adecco in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
All jobs contain valid city names

>**ACTUAL RESULTS:**
There are jobs does not contain valid city names

<br>

**Screenshots**
<img width="1424" alt="Screenshot at Feb 27 15-07-33" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/861f2eec-0d54-4bfa-9469-4e335b84a2a2">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/5d0ef18b-f044-4e2d-a60c-e54419b14219)
