### ISSUE TITLE
Damen - Load failed

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#148]
ENVIROMENT: production
COMPANY: Damen
URL: [Damen scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/damen/index.html)
Browser: Chrome
Device: Iphone
OS: IOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Firefox browser.

Steps:
1. Click on Firme from footer.
2. Enter Grubhub in the search bar.
3. Click the button under the company's logo.
4. Click the button "Run Scraper".

Expected result:
The scraper is updating

Actual result:
Load failed.
<img width="366" alt="Screenshot at Feb 28 16-49-08" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/e674f050-fcab-4f61-bd0e-a90f8d2a8b06">

**Comment by cristiol** [comment]
damen nu mai merge, l am scos din actions, adica codul nu mai ruleaza
