### ISSUE TITLE
Error in the name of the city from Edurom

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#15]
ENVIROMENT: production
COMPANY: Edurom
URL: [Edurom peviitor.ro](https://scrapers.peviitor.ro/src/edurom/)
Company's Career website: [Edurom official website](https://www.edurom.ro/it-jobs/?job__status_spec=open)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Edurom in the search bar.
3. Click the button under the company's logo.
4. Click the Run Scraper button.

Expected result:
1. All jobs contain valid city names

Actual result:
1. Jobs do not contain valid city names
<img width="1399" alt="bug edu2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/07e54bc5-86f5-43e3-b380-103b80f4d106">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/3b674752-e68d-4650-9728-65d0d24713b5)
