### ISSUE TITLE
Aceeasi firma de doua ori

### ISSUE THREAD

**Issue by OvidiuAl3x** [peviitor-ro/Scrapers_Cristi_Olteanu#151]
Ai scrapuit aceeasi firma de doua ori:
[fltechnics_scraper.py](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/blob/main/sites/fltechnics_scraper.py)

[FlTechincs_scraper.py](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/blob/main/sites/FlTechincs_scraper.py)
Prima e cea corecta, a doua e scris gresita numele

**Comment by cristiol** [comment]
l am sters pe [FlTechincs_scraper.py](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/blob/main/sites/FlTechincs_scraper.py)
