### ISSUE TITLE
Mambu - Incomplete job title

### ISSUE THREAD

**Issue by CristinaVoicu** [peviitor-ro/Scrapers_Cristi_Olteanu#155]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/mambu/index.html
Company_careers_url: [Mambu](https://careers-mambu.icims.com/jobs/search?ss=1&searchLocation=13526--)
Device: Laptop

OS: Windows 10 Pro 22H2
Browser: Google Chrome
Version: 122.0.6261.112

STEPS TO REPRODUCE:

1.Write "Mambu" in the search bar
2.Click on the company folder
3.Click on the "Run Scraper" button
4.Scroll down and observe the job titles for the job listings
5.Navigate to and click on the "Careers" button on the logo box

EXPECTED RESULTS:
The job titles should accurately reflect the information provided by the official website.

ACTUAL RESULTS:
Job title is listed as incomplete for one job.

![Capture](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/316df1ef-a33e-467c-a779-8fad5d552cfa)
![Capture1](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/49d3873b-b17e-4566-b80b-5a9b7ec2717e)
![Capture2](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/c81bdcab-6c41-4340-b303-d3abef9230ee)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/87c1207e-bfd9-4e17-8987-1b22bda767ac)
