### ISSUE TITLE
Milwaukee - Wrong job location

### ISSUE THREAD

**Issue by CristinaVoicu** [peviitor-ro/Scrapers_Cristi_Olteanu#156]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/milwaukee/index.html
Company_careers_url: [Milwaukee](https://ttiemea.wd3.myworkdayjobs.com/ro-RO/TTI)
Device: Laptop

OS: Windows 10 Pro 22H2
Browser: Google Chrome
Version: 122.0.6261.112

STEPS TO REPRODUCE:

1.Write "Milwaukee" in the search bar
2.Click on the company folder
3.Click on the "Run Scraper" button
4.Scroll down and observe the job locations for the job listings
5.Navigate to and click on the "Targetare.ro" button on the logo box
6.Scroll down and observe the job location of the company

EXPECTED RESULTS:
The job locations should accurately reflect the information provided by the official website.

ACTUAL RESULTS:
Job location is listed as "Bucharest" instead of  "Cluj".

![Capture6](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/40c44212-d3dc-4b5d-a1f2-c8c57172f9ce)
![Capture7](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/fd394f5b-9181-408e-a953-4ff26638ab75)
![Capture8](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/97cbb2ff-f750-482b-a3ae-6e2eb1dc7406)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/aa7c81ed-1b2a-4eef-80c2-450110bb7f64)
