### ISSUE TITLE
N-able - Job types do not match the official website

### ISSUE THREAD

**Issue by CristinaVoicu** [peviitor-ro/Scrapers_Cristi_Olteanu#157]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/n-able/index.html
Company_careers_url: [N-able](https://careers.n-able.com/jobs)
Device: Laptop

OS: Windows 10 Pro 22H2
Browser: Google Chrome
Version: 122.0.6261.112

 
STEPS TO REPRODUCE:

1.Write "N-able" in the search bar
2.Click on the company folder
3.Click on the "Run Scraper" button
4.Scroll down and observe the job types for the job listings
5.Navigate to and click on the "Careers" button on the logo box

EXPECTED RESULTS:
The job types should accurately reflect the information provided by the official website.

ACTUAL RESULTS:
Job type is listed as "No job type".

![Capture](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/538851c8-0430-4ad7-800f-886ce3ab016e)
![Capture1](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/1d6762fe-544c-4e3f-9b90-a4dd7a020e6c)
![Capture3](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/b3b6e3e6-6ad6-4100-9c51-f940a5041edd)
![Capture4](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/53d09ae0-25f9-43fa-b3dc-c6cfe3401498)
![Capture5](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/55003d10-e664-47da-a814-ac8ccd018efa)
![Capture6](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/626b36eb-e861-4099-bf5b-0e92bc059fc4)
![Capture7](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/64a07a11-bee6-4f4f-aef3-2c3f3e3abe3e)
![Capture8](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/064196bd-0af4-4315-bdb9-e1b1e4f92e61)
![Capture9](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/80da1823-789d-4bf5-bb89-c925dd44e3ab)
![Capture10](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/387af6eb-368e-4bf4-b7d0-67c0c0ec3ea8)
![Capture11](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/4c8f5588-5a40-4a69-918d-139c41a8c040)
![Capture12](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/159782419/0c8ccc6e-fc36-4e06-bd00-4a70dcc771dd)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/87ccd5f4-b77d-47c2-9c4d-909fca19ec79)
