### ISSUE TITLE
nVent scraper job "ERP Analyst "location is not in Romania

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#158]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/nvent/
**Company_careers_url**: https://nvent.wd5.myworkdayjobs.com/en-US/nVent/
 Desktop: Pc desktop
```
OS: windows 11
Browser:Chrome
Version: 122.0.6261.129
```

 
### **STEPS TO REPRODUCE:**
1) Open Url in browser.
2) Click on "run scraper button".
3)Scrol down and check job "ERP Analyst".

>**EXPECTED RESULTS:**
Location for job "ERP Analyst" suppose to be in Romania.

>**ACTUAL RESULTS:**
Location is diplayed that is not in Romania.
<br>

**Screenshots**
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/45e42a6a-e494-4f49-aaff-93f7cc500155)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/8b0a10f5-a63a-4408-91b3-6804706cad01)
