### ISSUE TITLE
Rianpartners jobs location displayed is not a city in Romania

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#159]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/rianpartners/index.html
**Company_careers_url**: https://rian-partners.com/en/careers/
 Desktop: Pc desktop
```
OS: windows 11
Browser:Chrome
Version: 122.0.6261.129 
```

 
### **STEPS TO REPRODUCE:**
1) Open Url in browser.
2)Click on "run scraper button".
3)Scrol down and check job "LEAN MANUFACTURING ENGINEER" , "SALES MANAGER".

>**EXPECTED RESULTS:**
Jobs location is in Romania.

>**ACTUAL RESULTS:**
Jobs locations are displayed not in Romania.
<br>

**Screenshots**
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/dd0cf8c6-ea01-46fb-81c8-3ac5de09145b)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/80645ecc-19d8-4952-a343-8429cbb5bb60)

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/79ac0340-a1a6-489e-a793-c231ee89386a)
