### ISSUE TITLE
The number of jobs from Garett does not correspond with the official site

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#16]
ENVIROMENT: production
COMPANY: Garrett
URL: [Garrett peviitor.ro](https://peviitor.ro/rezultate?q=Garrett&country=Rom%C3%A2nia&page=1)
Company's Career website: [Garrett official website](https://ehth.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/requisitions?location=Romania&locationId=300000000275207&locationLevel=country&mode=location)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
1. Enter Garrett in the search bar.
2. Click the button the company logo.

Expected results:
The number of jobs on [pe.viitor.ro](https://peviitor.ro/rezultate?q=Garrett&country=Rom%C3%A2nia&page=1) corresponds to the number of jobs on [Garrett](https://ehth.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/requisitions?location=Romania&locationId=300000000275207&locationLevel=country&mode=location) official website

Actual result:
The number of jobs on [pe.viitor.ro](https://peviitor.ro/rezultate?q=Garrett&country=Rom%C3%A2nia&page=1) do not correspond to the number of jobs on [Garrett](https://ehth.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/requisitions?location=Romania&locationId=300000000275207&locationLevel=country&mode=location) official website
<img width="1465" alt="bug garett1" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/abb99fd5-bbb1-44c4-9265-d717c61f454d">
<img width="1242" alt="bug garett 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/069a20f6-ab47-472a-9de6-b00ed1cf713c">

**Comment by cristiol** [comment]
At this moment, there are 43 jobs. https://peviitor.ro/rezultate?q=Garrett&country=Rom%C3%A2nia&page=1![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/cf91da6a-d579-4708-9fe7-7f79b948e417)

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/ce06b863-2565-47c7-8f8d-1e5aef6a476a)

**Comment by AdelinaGuliman** [comment]
Changes have occurred.
<img width="654" alt="bug Garrett1 1" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/ab729a20-b656-496f-8295-9f7e9c682408">
<img width="730" alt="bug Garrett" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/d7cc1f6d-a8a4-4b9d-b29d-e2b4b231c42d">

**Comment by cristiol** [comment]
The scraper is working fine.
This is just a delay between the time the Garrett website updates and the time the scraper runs. If you press the 'run scraper' button, the number of jobs will match

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/f0920691-8aaf-495d-820a-b3e966f93cfb)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/b14c7da2-f651-4756-a5b3-892841d55ba1)

**Comment by AdelinaGuliman** [comment]
case closed
