### ISSUE TITLE
Ramboll  scraper jobs do not match jobs number on the recruiter site

### ISSUE THREAD

**Issue by OctavianGriga** [peviitor-ro/Scrapers_Cristi_Olteanu#160]
ENVIROMENT: production
URL:https://scrapers.peviitor.ro/src/ramboll/index.html
**Company_careers_url**: https://careers.smartrecruiters.com/Ramboll3?search=romania
 Desktop: Pc desktop
```
OS: windows 11
Browser: Chrome
Version: 123.0.6312.59
```

 
### **STEPS TO REPRODUCE:**
1) Open URL in browser.
2) Click "run scraper".
3)Scroll down and see the jobs.

>**EXPECTED RESULTS:**
Number of jobs to match from scraper with the official site.

>**ACTUAL RESULTS:**
Number of jobs do not match and there is 2 extra possition displayed.
<br>

**Screenshots**
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/548cd94d-3188-422e-ba8f-f902ea8e9bf7)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/128740240/8e696ca4-bd25-4061-a474-181c3a629e98)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/872c9c1b-79bb-4896-9e4e-dd196515712b)
