### ISSUE TITLE
HiveMQ - Job listings displayed for Germany and other non-Romanian countries

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#165]
ENVIROMENT:  production
URL: https://peviitor.ro/
**Company_careers_url**: [HiveMQ](https://boards.eu.greenhouse.io/hivemq)
 Desktop:
```
OS: Sonoma 14.4.1
Browser: Chrome
Version: 124.0.6
```

 
### **STEPS TO REPRODUCE:**
1) Click on the search field
2) Type "HiveMQ" in the search bar
3) Click on the "Cauta" button
4) Click on "Catre site" button on one of the job cards
5) Observe the country displayed on the job description page

>**EXPECTED RESULTS:**
Jobs listings are published as remote, hybrid or on-site in Romania.

>**ACTUAL RESULTS:**
There are jobs with locations in other countries than Romania.

<br>

**Screenshots**
...
<img width="657" alt="Screenshot 2024-06-03 at 19 09 24" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/08871ce2-6af0-4da7-bf72-502f818d3d55">

<img width="568" alt="Screenshot 2024-06-03 at 19 10 24" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/9444ccde-8729-41ae-bdb8-62618f887285">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/user-attachments/assets/30fdbeda-360f-49f6-a7d8-2a0bbe078432)

**Comment by iBixee** [comment]
Thank you!
