### ISSUE TITLE
Antal - Link does not correspond 

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#166]
ENVIROMENT: ui.validator
URL: [Antal-Validator UI](https://admin.peviitor.ro/jobs/Antal)
**Company_careers_url**: [Antal](https://www.antal.com/jobs?keywords=%C2%A7or=&location=1721&type=&page=)
 Desktop:
```
OS: MacOS
Browser: Safari
```
### **STEPS TO REPRODUCE:**
1) Click on "Companii"
2) Click in the "Cauta aici..." search bar.
3) Write "Antal"
4) Click on "Vizualizeaza joburi"
5) Scroll-down to "Inginer Cantitati - Suceava"
6) Click on " Catre job"

>**EXPECTED RESULTS:**
The job description of the position "Inginer Cantitati - Suceava" opens 

>**ACTUAL RESULTS:**
The link does not correspond to the "Inginer Cantitati - Suceava" position
<br>

https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/b80a1315-f44e-47d5-b5ba-a45d842ae704

**Comment by cristiol** [comment]
I cant reproduce the bug. I tried many times and it works as expected

**Comment by AdelinaGuliman** [comment]
Now it works. I ran the scraper as you told me before writing this bug report. Apparently the validator is playing tricks on me!
