### ISSUE TITLE
The number of jobs from GoPro does not correspond 

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#17]
ENVIROMENT: production
COMPANY: GoPro
URL: [GoPro peviitor.ro](https://scrapers.peviitor.ro/src/gopro/)
Company's Career website: [GoPro official website](https://jobs.gopro.com/jobs/country/romania#/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:
1. Click on Firma button from the footer.
2. Enter GoPro in the search bar. 
3. Click the button under the logo company.
4. Click the Run Scraper button.

Expected results:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/gopro/) corresponds to the number of jobs on [GoPro](https://jobs.gopro.com/jobs/country/romania#/)

Actual result:

The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/gopro/) do not correspond to the number of jobs on [GoPro](https://jobs.gopro.com/jobs/country/romania#/)

<img width="1080" alt="Gopro bug1" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/4ec8169c-77e9-4bd4-bf1d-803e34cbacd7">
<img width="1021" alt="gopro bug 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/3ae56b79-5e94-4e43-8e54-32e4e991f5a8">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/7788b381-d52e-4db2-8b7f-b10d9c2e53e2)
