### ISSUE TITLE
Prohuman - Jobs from another countries are not allowed

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#179]
ENVIROMENT: Validator.ui
URL: [Validator](https://admin.peviitor.ro/jobs/Prohuman)
**Company_careers_url**: [Prohuman](https://www.prohuman.ro/candidati/jobs/Production-Manager-Republica-Moldova)
 Desktop:
```
OS: MacOS
Browser: Chrome
```
### **STEPS TO REPRODUCE:**
1) Enter the [link](https://admin.peviitor.ro/jobs/Prohuman)
2) Select "Nepublicate" from the filter select.sorting
3) Scroll down to "Production Manager (Republica Moldova)" title

>**EXPECTED RESULTS:**
Republica Moldova is not in Romania, so the job must not be listed.

>**ACTUAL RESULTS:**
Jobs from Republica Moldova does not exist.

<br>
**Screenshots**
<img width="1041" alt="Screenshot at Jul 04 15-05-20" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/7f6f4b2a-1d93-402d-9bbf-1aec3a99559d">

**Comment by cristiol** [comment]
fixed please retest
