### ISSUE TITLE
The numbers of jobs from Ecolab does not correspond with the official site

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#18]
ENVIROMENT: production
COMPANY: Ecolab
URL: [Ecolab peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1)
Company's Career website: [Ecolab official website](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:

Enter Ecolab in the search bar.
Click the company logo.
Expected results:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1) corresponds to the number of jobs on [Ecolab](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25) official website

Actual result:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ECOLAB&country=Rom%C3%A2nia&page=1) do not correspond to the number of jobs on [Ecolab](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25) official website
<img width="1206" alt="bug ecolab1 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/16c0639f-734c-4222-a2ae-cca3a4241924">
<img width="1146" alt="bug ecolab 1 2 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/fffa1ab0-383b-4041-a147-3c3c4a8f46c5">

**Comment by cristiol** [comment]
The scraper is working well; the data is extracted directly from the API link below, and the job counts match. The discrepancy between the number of jobs posted on the Ecolab website and the number of jobs on the site (link below) is a bug on the Ecolab website.

https://ecolab.wd1.myworkdayjobs.com/en-US/Ecolab_External/?locations=88d5fb29f85801018b6c2ac810e20000&locations=8ad79cd2b0580101f03004df87fb0000

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/98fbf9a7-cfcf-47f9-ad24-fba1c5c81f87)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/35e7c992-6a52-4d9a-9bf4-cd74e5f0d858)
