### ISSUE TITLE
Adecco - Duplicate job

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#189]
ENVIROMENT: ui.validator
URL: [Adecco-Validator UI](https://admin.peviitor.ro/jobs/Adecco)
**Company_careers_url**: [Antal](https://www.adecco.ro/jobs/job/a1h6M0000093VvtQAE)
 Desktop:
```
OS: MacOS
Browser: Chrome
```
### **STEPS TO REPRODUCE:**
1) Click on "Companii"
2) Click in the "Cauta aici..." search bar.
3) Write "Adecco"
4) Click on "Vizualizeaza joburi"
5) Scroll-down to "Buyer - Chemicals (Food, Feed, Pharma)"

>**EXPECTED RESULTS:**
There is only one job with this title

>**ACTUAL RESULTS:**
This job is duplicated. There is another one with the same link

<img width="742" alt="Screenshot at Jul 12 15-58-49" src="https://github.com/user-attachments/assets/b19a3ff8-8a46-48fb-9b97-3abb202bc1c3">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/user-attachments/assets/b62f973c-6456-4d9b-8418-e8d06c3f87b8)
