### ISSUE TITLE
Adecco- Not working

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#190]
ENVIROMENT: Validator.ui
URL: https://admin.peviitor.ro/account
 Desktop:
```
OS: MacOS
Browser: Chrome
```

 
### **STEPS TO REPRODUCE:**
1) Click on "Cont"
2) Click on "Scrapers_Cristi_Olteanu" repository
3) Click on "Adecco" company

>**EXPECTED RESULTS:**
The scraper is updated marked with a check mark

>**ACTUAL RESULTS:**
The scraper does not run
<br>

**Screenshots**
<img width="353" alt="Screenshot at Jul 15 16-03-17" src="https://github.com/user-attachments/assets/36785193-0685-4fde-929e-15f1298c29e2">

**Comment by cristiol** [comment]
It seems to work fine.
![image](https://github.com/user-attachments/assets/7f2c6b43-ceab-4b1d-b6f9-d84aac55f2e7)
