### ISSUE TITLE
A job link for "hirschmann" company in scraper is wrong

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/Scrapers_Cristi_Olteanu#191]
ENVIROMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

 
### **STEPS TO REPRODUCE:**
1) ...Opne URL in browser
2) ..Type "hirschmann" in the search bar
3) Click on "Vizaualizeaza joburi"
4) Press the "Catre job" button of the only job listed

>**EXPECTED RESULTS:**
A link with the job must be open

>**ACTUAL RESULTS:**
The link is wrong

The correct link for job is:
https://career.hirschmann-automotive.com/en/job-detail/sap-abap-developer

![Hirschmann 1](https://github.com/user-attachments/assets/87ee8a89-93ca-4e32-a3a6-950ff38bf0c5)

![Hirschmann 2](https://github.com/user-attachments/assets/2bc7b125-23d0-4d1a-b959-2f0daa8b54ae)

**Comment by cristiol** [comment]
the scraper was deleted
