### ISSUE TITLE
The scraper does not load correctly the number of jobs on Hirschmann

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/Scrapers_Cristi_Olteanu#192]
ENVIROMENT: validator
URL: [validator](https://admin.peviitor.ro/account)

**Company_careers_url: [hirschmann-automotive](https://career.hirschmann-automotive.com/en/targu-mures-romania)**

Browser: Chrome
Device: Laptop
OS: Windows 10

### **STEPS TO REPRODUCE:**
1) ...Enter url in browser
2) ...Go to search bar and type "Hirschmann"  
3) Click on "Vizualizeaza joburi"
4) Go to [hirschmann-automotive](https://career.hirschmann-automotive.com/en/targu-mures-romania) 

>**EXPECTED RESULTS:**
...The page shows the same number of jobs as on the validator

>**ACTUAL RESULTS:**
...Page from "https://admin.peviitor.ro/jobs/Hirschmann" show one number of jobs , official site show different number.

**Screenshots**

Validator

![Hirschmann 3](https://github.com/user-attachments/assets/ede24aa7-7214-4369-a669-d9715c558354)

**Company_careers_url: [hirschmann-automotive](https://career.hirschmann-automotive.com/en/targu-mures-romania)**

![Hirschmann-carriers ](https://github.com/user-attachments/assets/5111dbdc-5802-4802-b312-3858b7d94457)

**Comment by cristiol** [comment]
the scraper was deleted
