### ISSUE TITLE
Hoffman-cele doua job-uri nu sunt reprezentative pentru Romania 

### ISSUE THREAD

**Issue by auroracreta2008** [peviitor-ro/Scrapers_Cristi_Olteanu#193]
ENVIROMENT: validator ui
URL: https://admin.peviitor.ro/jobs/Hoffman
**Company_careers_url**: [Hoffman_1](https://career.hoffmann-group.com/Integration-API-Developer-mwd-de-j1288.html)
[Hoffman_2](https://career.hoffmann-group.com/Enterprise-Integration-Platform-Lead-mwd-de-j1285.html)
```
OS: Microsoft
Browser: Chrome

```

 
### **STEPS TO REPRODUCE:**
1) Faceti click pe [link-ul](https://admin.peviitor.ro/jobs/Hoffman)
2) Mergeti la job-ul Dezvoltator API de integrare (m/w/d)
3) Faceti click Catre job 

>**EXPECTED RESULTS:**
Job-ul este pentru Romania 

>**ACTUAL RESULTS:**
Job-ul nu este pentru Romania
<br>

**Screenshots**
![Screenshot 2024-08-01 155809](https://github.com/user-attachments/assets/d192761d-5774-4636-9b41-a2d888647202)

**Comment by cristiol** [comment]
the jobs it s not available anymore
![image](https://github.com/user-attachments/assets/1bc36b7b-d781-4794-be18-c76bd92a8e67)
