### ISSUE TITLE
 Hirschmann- the scraper stopped running

### ISSUE THREAD

**Issue by szemama** [peviitor-ro/Scrapers_Cristi_Olteanu#194]
ENVIROMENT: validator UI
URL: https://admin.peviitor.ro/jobs/Hirschmann
 
 Desktop:
```
OS:  Windows
Browser: Chrome
 
```

 
### **STEPS TO REPRODUCE:**
1) enter the [link](https://admin.peviitor.ro/jobs/Hirschmann)
2) observe the graph 

>**EXPECTED RESULTS:**
the graph is updated in real time

>**ACTUAL RESULTS:**
the scraper stopped running since 16th of July

<br>

**Screenshots**
![image](https://github.com/user-attachments/assets/c3b70fd3-5945-47c9-b9bb-f2593ae39ee4)

**Comment by cristiol** [comment]
The scraper doesn't have jobs and does not run anymore.
