### ISSUE TITLE
Hoffman-cele doua job-uri nu sunt reprezentative pentru Romania

### ISSUE THREAD

**Issue by auroracreta2008** [peviitor-ro/Scrapers_Cristi_Olteanu#195]
ENVIROMENT: validator ui
URL: https://admin.peviitor.ro/jobs/Hoffman
**Company_careers_url**: [Hoffman_1](https://career.hoffmann-group.com/Enterprise-Integration-Platform-Lead-mwd-de-j1285.html_)
[Hoffman_2](https://career.hoffmann-group.com/Integration-API-Developer-mwd-de-j1288.html)
 
```
OS: Microsoft
Browser: Chrome

```

 
### **STEPS TO REPRODUCE:**
1) Faceti click pe [link-ul](https://admin.peviitor.ro/jobs/Hoffman)
2) Mergeti la job-ul Lider platformă de integrare întreprindere (m/f/d)
3) Faceti click Catre job

>**EXPECTED RESULTS:**
Job-ul este pentru Romania

>**ACTUAL RESULTS:**
Job-ul nu este pentru Romania
<br>

**Screenshots**
![Screenshot 2024-08-01 164838](https://github.com/user-attachments/assets/b5018c3d-efc4-4c75-9c7b-ab3a5bb52a2c)

**Comment by cristiol** [comment]
not valid bug, the job is available for Romania
![image](https://github.com/user-attachments/assets/32bb6268-f656-4517-b046-d60852441a16)
