### ISSUE TITLE
Ascom - The scraper stopped running 

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#196]
ENVIROMENT: Validator.ui
URL: https://admin.peviitor.ro/jobs/Ascom
 Desktop:
```
OS: MacOS
Browser: Chrome
```

 
### **STEPS TO REPRODUCE:**
1) Click on "Cont"
2) Click on "Scrapers_Cristi_Olteanu" repository
3) Click on "Ascom" company to run scraper
4) Click on "Companii"
5) Type "Ascom" in "Cauta aici..." field
6) Click "Vezi joburile"

>**EXPECTED RESULTS:**
The graph shows the updated data from the last 24 hours

>**ACTUAL RESULTS:**
The scraper stopped running from 9 July
<br>

**Screenshots**
<img width="1467" alt="Screenshot at Aug 02 15-06-33" src="https://github.com/user-attachments/assets/af5f0adc-6204-4dd2-a7ca-c3cd5262b9ce">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/user-attachments/assets/1a7312da-66ba-4e81-847a-c097a17d015c)
