### ISSUE TITLE
Hootsuite-job-ul  "Escalation Technical Support Specialist" este afisat de doua ori

### ISSUE THREAD

**Issue by auroracreta2008** [peviitor-ro/Scrapers_Cristi_Olteanu#197]
ENVIROMENT: validator ui
URL: https://peviitor.ro/
**Company_careers_url**: [Hootsuite_](https://careers.hootsuite.com/job/?gh_jid=6071251#_)
 
```
OS:  Microsoft
Browser: Chrome

```

 
### **STEPS TO REPRODUCE:**
1) Faceti clik pe [link-ul](https://admin.peviitor.ro/)
2) Mergeti la job-ul  Specialist Suport Tehnic Escaladare

>**EXPECTED RESULTS:**
Job-ul este afisat de doua ori

>**ACTUAL RESULTS:**
Job-ul este afisat o singura data
<br>

**Screenshots**
![Screenshot 2024-08-02 164302](https://github.com/user-attachments/assets/3adc40b3-cc6d-4da0-bfea-49e6b1473e9f)

**Comment by cristiol** [comment]
There are two different jobs with different URLs.
