### ISSUE TITLE
Hootsuite-job-ul Specialist Suport Tehnic Escaladare nu este reprezentativ pentru Romania

### ISSUE THREAD

**Issue by auroracreta2008** [peviitor-ro/Scrapers_Cristi_Olteanu#198]
ENVIROMENT: validator ui
URL: https://peviitor.ro/
**Company_careers_url**: [Hootsuite_](https://admin.peviitor.ro/jobs/Hootsuite_)

```
OS:  Microsoft
Browser: Chrome

```

 
### **STEPS TO REPRODUCE:**
1) Faceti click pe  [link-ul](https://peviitor.ro/)
2) Mergeti la job-ul Specialist Suport Tehnic Escaladare
3) Faceti click Catre job

>**EXPECTED RESULTS:**
Job-ul este pentru Romania

>**ACTUAL RESULTS:**
Job-ul nu este pentru Romania
<br>

**Screenshots**
![Screenshot 2024-08-02 170537](https://github.com/user-attachments/assets/e0ccb800-44b0-437e-8d47-5f86520be840)

**Comment by cristiol** [comment]
The job posting it from Romania, so it is not a valid bug, and I will close the issue.
