### ISSUE TITLE
Leroymerlin: is missing the analitycs diagram 

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/Scrapers_Cristi_Olteanu#199]
ENVIROMENT: validator
URL: https://admin.peviitor.ro/

OS: Windows 11
Browser: Chrome 
Version: 127.0.6533.74

1) Enter url in browser
2) Go to "https://admin.peviitor.ro/" 
3) Type "Leroymerlin" in the search bar  and click on "Vizualizare joburi (50)".

>**EXPECTED RESULTS:**
An  diagram of the  scraper must appear

>**ACTUAL RESULTS:**
The analytics diagram of the scaper is missing

![Leroy Merlin diagram](https://github.com/user-attachments/assets/65adb86b-c521-455f-8618-5b06a26dc925)

**Comment by lalalaurentiu** [comment]
@cristiol Validatorul nu mai primeste date de la scraper ca are un obiect neacceptat
![Screenshot 2024-08-28 at 18 04 37](https://github.com/user-attachments/assets/c078acba-c67a-421b-bcbb-2bb326427e6b)
Keywordul "Hibrid" nu este permis ci dor on-site, remote sau hybrid

**Comment by cristiol** [comment]
s a rezolvat 
![image](https://github.com/user-attachments/assets/805c84b7-1be9-449c-bfcd-6d2c177957aa)
