### ISSUE TITLE
Description "About us" is missing

### ISSUE THREAD

**Issue by AniteiAlina** [peviitor-ro/Scrapers_Cristi_Olteanu#2]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
macOS: 13.4

STEPS TO REPRODUCE:

Open "https://scrapers.peviitor.ro/".
Type “Adecco” on the search bar.
Click on “Adecco”
Check the section “About us”

EXPECTED RESULTS:
See the description “About us”

ACTUAL RESULT:
The description "About us" is missing

<img width="1027" alt="about us" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/131695035/226c5f59-644a-4884-bd54-0311f86853ca">

**Comment by lalalaurentiu** [comment]
Deprecated...
