### ISSUE TITLE
The numbers of jobs from HKR does not correspond with the official site

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#20]
ENVIROMENT: production
COMPANY: HKR
URL: [HKR peviitor.ro](https://peviitor.ro/rezultate?q=hkr&country=Rom%C3%A2nia&page=1)
Company's Career website: [HKR official website](https://jobs.eu.lever.co/hkr/?location=Romania)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:

1. Enter HKR in the search bar.
2. Click the company logo.

Expected results:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=hkr&country=Rom%C3%A2nia&page=1) corresponds to the number of jobs on [HKR](https://jobs.eu.lever.co/hkr/?location=Romania) official website

Actual result:

The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=hkr&country=Rom%C3%A2nia&page=1) do not correspond to the number of jobs on [HKR](https://jobs.eu.lever.co/hkr/?location=Romania) official website
<img width="1251" alt="bug hkr1" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/2e1d9ec0-0ad2-4717-a2e6-fd4669e15267">
<img width="909" alt="bug hkr1 1" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/dd236119-946f-4730-8a00-db668e4772aa">

**Comment by cristiol** [comment]
It's not a bug; the scraper is functioning correctly. On the company's website, there are 9 job listings in Romania and one in Bucharest, which adds up to a total of 10 job listings.

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/9fa51b82-9d17-4c7a-9f7c-bc7070599677)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/26b15491-2542-4f28-9679-8c67ef3d50cd)
