### ISSUE TITLE
CMED job link is not find

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/Scrapers_Cristi_Olteanu#200]
ENVIROMENT: Valodator UI
URL: https://admin.peviitor.ro/accont

 Desktop:
```
OS: Windows
Browser: Chrome
Version:  128.0.6613.120
```

 
### **STEPS TO REPRODUCE:**
Click on "Companii"
Click in the "Cauta aici..." search bar.
Type "CMED"
Click on "Vizualizeaza joburi"
Scroll-down to "Advanced Safety Officer (CP57Ti584)"
Click on " Catre job"

>**EXPECTED RESULTS:**
The job description of the position "Inginer Cantitati - Suceava" opens

>**ACTUAL RESULTS:**
The link goes to another job that is not find
<br>

**Screenshots**
...
![image](https://github.com/user-attachments/assets/f1fbf6ae-f5ef-45a6-9891-396f64e46306)

**Comment by cristiol** [comment]
Scraper is still working, but for this company there are no more jobs available for Romania.
