### ISSUE TITLE
Ge - International Job Listings Displayed in Romania Territory Coverage

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#205]
ENVIROMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [GE](https://admin.peviitor.ro/jobs/Ge)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Safari
Version: 17.6
```

 
### **STEPS TO REPRODUCE:**
1) Type "Ge" in the search field
2) Click on the "Vizualizeaza Joburi" button
3) Observe the job titles in the job list

>**EXPECTED RESULTS:**
Job listings for Romania territory are visible on the page.

>**ACTUAL RESULTS:**
International job listings can be found on the page.
_There are also duplicated job listings._

<br>

**Screenshots**
...
<img width="1328" alt="Screenshot 2024-09-10 at 17 08 18" src="https://github.com/user-attachments/assets/22e27f43-3861-45d5-8867-60b298afbd56">

<img width="1287" alt="Screenshot 2024-09-10 at 17 08 30" src="https://github.com/user-attachments/assets/19c45eed-4ad9-4641-8b5a-3545f6f45b83">

<img width="1307" alt="Screenshot 2024-09-10 at 17 08 43" src="https://github.com/user-attachments/assets/2d01952c-88aa-4331-8185-fd01166d8167">

<img width="1326" alt="Screenshot 2024-09-10 at 17 09 07" src="https://github.com/user-attachments/assets/643a2651-8fb8-4556-a326-551f36c5bafb">

<img width="1330" alt="Screenshot 2024-09-10 at 17 09 27" src="https://github.com/user-attachments/assets/b308edd7-ec3e-4a19-bc57-0fbb376c3dac">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/user-attachments/assets/4a7820bf-4c2e-4849-86ef-dd71d0d6e9d7)
