### ISSUE TITLE
Bookingholdings - No data exists for this company in the database.

### ISSUE THREAD

**Issue by dmariancatalin** [peviitor-ro/Scrapers_Cristi_Olteanu#206]
ENVIROMENT: validatori-ui
URL: https://admin.peviitor.ro/
**Company**: Bookingholdings
 Desktop:
```
OS: Win 11 Home
Browser: Microsoft Edge
Version: Version 128.0.2739.67 (64-bit)
```

Precondition:
The [website](https://admin.peviitor.ro/) is up and running.
 
### **STEPS TO REPRODUCE:**
1) Click on ”Cauta aici” field.
2) Type ”Bookingholdings”.
3) Click on ”Vizualizeaza Joburi”.

>**EXPECTED RESULTS:**
Data for this company exists in the database.

>**ACTUAL RESULTS:**
No data exists for this company in the database.

<br>

**Screenshots**
![image](https://github.com/user-attachments/assets/bdd0a3ff-af02-4076-af64-0a4eec912299)

**Comment by cristiol** [comment]
there are no more job available for Romania
