### ISSUE TITLE
404 Error: Job Link for 'Lead RTR Accountant - Booking Holdings Romania' Returns Page Not Found

### ISSUE THREAD

**Issue by dmariancatalin** [peviitor-ro/Scrapers_Cristi_Olteanu#207]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: [Company's _name_](Company's careers _URL_)
 Desktop:
```
OS: Win 11 Home
Browser: Microsoft Edge
Version: Version 128.0.2739.67 (64-bit)
```

Precondition:
The [website](https://admin.peviitor.ro/) is up and running.
 
### **STEPS TO REPRODUCE:**
1) Click on ”Cauta aici” field.
2) Type ”Bookingholdings”.
3) Click on ”Vizualizeaza Joburi”.
4) Click on ”Către job”.

>**EXPECTED RESULTS:**
We should go to the website where the job is located.

>**ACTUAL RESULTS:**
The website doesn't load and gives us a 404 error.
<br>

**Screenshots**
![image](https://github.com/user-attachments/assets/56f6cc86-cc42-4b77-af7f-f05de5c4cbee)

**Comment by cristiol** [comment]
related to issue 206
