### ISSUE TITLE
Garrett - Job numbers do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#218]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Garrett](https://admin.peviitor.ro/jobs/Garrett)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Safari
Version: 17.6
```

### **STEPS TO REPRODUCE:**
1) Type "Garrett" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job" and observe the official number of jobs on the company's official page
5) Go to peviitor.ro and type "Garrett" in the search field
6) Observe the number of jobs listed under Garrett company

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
More jobs on the validator and on peviitor than on the official website.

<br>

**Screenshots**
...
<img width="349" alt="Screenshot 2024-09-13 at 17 27 42" src="https://github.com/user-attachments/assets/8499fe74-b5fd-4996-a3ce-c836a1bcc96a">

<img width="607" alt="Screenshot 2024-09-13 at 17 28 03" src="https://github.com/user-attachments/assets/e63eed1d-463d-4057-8a94-a28792438173">

<img width="533" alt="Screenshot 2024-09-13 at 17 28 12" src="https://github.com/user-attachments/assets/709515b7-d331-46ef-a40c-b9b72c959047">

**Comment by cristiol** [comment]
![image](https://github.com/user-attachments/assets/6fe8889a-5830-4c1e-9fde-60fdf2f8cf18)
![image](https://github.com/user-attachments/assets/66a28b08-59cb-4df0-8aee-ceacdbbacb7c)
![image](https://github.com/user-attachments/assets/7d155cf6-fca0-4642-8361-ef4fa9a8b68d)

**Comment by iBixee** [comment]
Super! Thank you!
