### ISSUE TITLE
Error in the name of the city from Humanrise

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#22]
ENVIROMENT: production
COMPANY: Humanrise
URL: [Humanrise peviitor.ro](https://scrapers.peviitor.ro/src/humanrise/)
Company's Career website: [Humanrise official website](https://www.careers-page.com/humanrise)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:

Click on Firme from footer.
Enter Humanrise in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.

Expected result:

All jobs contain valid city names

Actual result:

Jobs do not contain valid city names
<img width="1342" alt="bug Humanrise" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/722eb16b-b833-4d8b-8493-3ac221f3502c">

**Comment by cristiol** [comment]
fixed 

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/568f9706-9437-4076-89f9-dcf731b28a2e)
