### ISSUE TITLE
Wavestone - Job numbers do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#231]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Wavestone](https://admin.peviitor.ro/jobs/Wavestone)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 127
```

### **STEPS TO REPRODUCE:**
1) Type "Wavestone" in the search field
2) Observe the number of jobs inside the company card
3) Compare the number of jobs in Validator with the ones on peviitor.ro

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
More jobs on the validator and on the official website than on peviitor.ro.

<br>

**Screenshots**
...
<img width="336" alt="Screenshot 2024-09-16 at 21 34 29" src="https://github.com/user-attachments/assets/233f1729-e69e-40d1-a5c5-b8ee98fcbf5a">

<img width="1106" alt="Screenshot 2024-09-16 at 21 34 49" src="https://github.com/user-attachments/assets/d59c25bc-70f6-443a-a360-aaa0e08b1360">

<img width="1104" alt="Screenshot 2024-09-16 at 21 36 19" src="https://github.com/user-attachments/assets/ab544f95-b97c-4980-9c0c-bd0d09cb1e1d">

**Comment by cristiol** [comment]
![image](https://github.com/user-attachments/assets/01c0980c-f0db-4e11-9720-dd5cbb6e97bb)

**Comment by iBixee** [comment]
Thank you.
