### ISSUE TITLE
"Hivemq" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/Scrapers_Cristi_Olteanu#239]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Hivemq"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working properly.

![image](https://github.com/user-attachments/assets/3c2ae65f-e1d9-454e-b659-caff87764a24)

**Comment by cristiol** [comment]
![image](https://github.com/user-attachments/assets/9a1c5bfc-991e-4363-b239-850ed8ffe117)

**Comment by Florin201092** [comment]
Fixed!
