### ISSUE TITLE
Error in the name of the city from Globalstep

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#24]
ENVIROMENT: production
COMPANY: Globalstep
URL: [Globalstep peviitor.ro](https://scrapers.peviitor.ro/src/globalstep/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Globalstep in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.

Expected result:
All jobs contain valid city names

Actual result:
Jobs do not contain valid city names
<img width="1493" alt="Screenshot at Nov 14 14-48-10" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/a567d8fd-523a-40b0-a15b-348833e70df0">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/6e1ee1d0-cb81-48e1-977d-3dbb7110a308)
