### ISSUE TITLE
"Fotc" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/Scrapers_Cristi_Olteanu#242]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Fotc"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since properly.

![image](https://github.com/user-attachments/assets/ca8b7e56-0462-461f-ba69-10ed91596157)

**Comment by cristiol** [comment]
fixed
all good now 
![image](https://github.com/user-attachments/assets/9e2d244b-ab99-4e4f-980b-8f02755de964)

**Comment by Florin201092** [comment]
Fixed!
