### ISSUE TITLE
Hirschmann - Job numbers do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#246]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Hirschmann](https://admin.peviitor.ro/jobs/Hirschmann)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Safari
Version: 17.6
```

### **STEPS TO REPRODUCE:**
1) Type "Hirschmann" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job" and observe the official number of jobs on the company's official page

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
More jobs on the official website than on the validator.

<br>

**Screenshots**
...

<img width="384" alt="Screenshot 2024-09-24 at 20 06 53" src="https://github.com/user-attachments/assets/98ee711f-acae-4a9c-985b-74d1c6e322e3">

<img width="1313" alt="Screenshot 2024-09-24 at 20 06 08" src="https://github.com/user-attachments/assets/2ff05179-7fba-4d22-aa6a-bda9755e161a">

**Comment by cristiol** [comment]
scraperul asta l am sters ptr ca nu mai functiona

**Comment by iBixee** [comment]
Au mai multe joburi listate pentru Romania, nu-l putem pune din nou in functiune?

**Comment by cristiol** [comment]
am incercat si acum sa l refac dar n am gasit o solutie sa l refac

**Comment by iBixee** [comment]
Trecem la nefunctional atunci si mergem mai departe.
