### ISSUE TITLE
Lectra: is missing the diagram analytic

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/Scrapers_Cristi_Olteanu#249]
ENVIROMENT:validator.ui
URL: https://admin.peviitor.ro/

 Desktop:
```
OS: Windows
Browser: Chrome 
Version: 129.0.6668.71
```

 
### **STEPS TO REPRODUCE:**
1) Enter url in browser
2) Go to "https://admin.peviitor.ro/" 
3) Type "lectra" in the search bar  and click on "Vizualizare joburi (2)".

>**EXPECTED RESULTS:**
A diagram analytic of the  scraper must appear

>**ACTUAL RESULTS:**
The diagram analytic  of the scaper is missing
<br>

**Screenshots**
...
![Missing_diagram](https://github.com/user-attachments/assets/54678f63-65e3-4d80-835b-9e83265eaeca)

**Comment by cristiol** [comment]
nu e neparat bug in conditiile in care scraperul nu mai aduce joburi ptr ca firma respectiva nu mai are joburi disponibile ptr Romania atunci nici acel grafic nu are ce joburi sa afiseaza. In cazul in care scraperul ar fi adus joburi si graficul nu mergea atunci era un bug
