### ISSUE TITLE
Error in the name of the job title from Gopro

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#25]
ENVIROMENT: production
COMPANY: Gopro
URL: [Gopro peviitor.ro](https://scrapers.peviitor.ro/src/gopro/)
Company's Career website:[Gopro official website](https://jobs.gopro.com/jobs/country/romania#/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Gopro in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.

Expected result:
All jobs contain valid job title.

Actual result:
Jobs do not contain valid job title.
<img width="1480" alt="Screenshot at Nov 14 14-55-10" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/ed8b6ba4-6f24-4128-9677-b8455a0c5626">
<img width="404" alt="Screenshot at Nov 14 14-55-36" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/7b4dcc9f-cc92-4281-be3d-e62fbe945880">

**Comment by cristiol** [comment]
fixed 

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/87886c16-b4d4-42eb-8931-d9ab1b472e43)
