### ISSUE TITLE
Veridion - Job numbers do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#253]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Veridion](https://admin.peviitor.ro/jobs/Veridion)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "Veridion" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job" and observe the official number of jobs on the company's official page

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
More jobs on the official website than on the validator.

<br>

**Screenshots**
...
<img width="372" alt="Screenshot 2024-09-25 at 23 14 26" src="https://github.com/user-attachments/assets/c6b6fb6a-941c-4596-a437-3eac243f3b07">

<img width="1234" alt="Screenshot 2024-09-25 at 23 14 07" src="https://github.com/user-attachments/assets/0417f580-ad62-482c-a925-c38046379026">

**Comment by cristiol** [comment]
poti pune si linkul de pe site ul veridion ca nu l gasesc ?

**Comment by iBixee** [comment]
It's stable now.
