### ISSUE TITLE
Rianpartners - Official website contains 2 job listing branches, we're missing one

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#258]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Rianpartners](https://admin.peviitor.ro/jobs/Rianpartners)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "Rianpartners" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job"
5) Navigate and hover over "available jobs"
6) Click on "office jobs" and compare them with the Validator jobs
7) Navigate and hover over "jobs in production"
8) Observe the "jobs in production" are missing from the Validator

>**EXPECTED RESULTS:**
Job listings are matching the official website.

>**ACTUAL RESULTS:**
There are 2 branches of job listings on the official website.

<br>

**Screenshots**
...
<img width="1276" alt="Screenshot 2024-10-10 at 16 11 21" src="https://github.com/user-attachments/assets/fcf6a6fe-8ea4-43a7-aeea-f718de4c246f">

<img width="277" alt="Screenshot 2024-10-10 at 16 11 07" src="https://github.com/user-attachments/assets/ecbe9526-ea40-4fea-b4e1-5d5a3828d64b">

_**Additional information:** Link to the missing job listings: [Jobs+](https://rian-partners.com/en/rian-partners-jobs-pitesti-jobs-in-production/#)_

**Comment by cristiol** [comment]
fixed
![image](https://github.com/user-attachments/assets/a8846166-d3a0-4fc8-8513-eb6a81f54189)

**Comment by iBixee** [comment]
Thank you!
