### ISSUE TITLE
Rws - 2 missing jobs due to Romania listing not being visible

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#259]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Rws](https://admin.peviitor.ro/jobs/Rws)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "Rws" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job"
5) Navigate to the job listings and observe there are 2 job listings for United Kingdom that are also being listed for Romania as well.

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
More jobs on the official website than on the validator.

<br>

**Screenshots**
...

<img width="807" alt="Screenshot 2024-10-10 at 16 57 35" src="https://github.com/user-attachments/assets/7cf57c0b-8440-4f59-b222-53de63033061">

<img width="494" alt="Screenshot 2024-10-10 at 16 57 48" src="https://github.com/user-attachments/assets/c3a20a43-63ff-452a-bfd0-966346f46d85">

**Comment by cristiol** [comment]
fixed

![image](https://github.com/user-attachments/assets/71bfa290-3ff6-42e7-962d-9c847427fa03)
https://globalcareers-rws.icims.com/jobs/search?ss=1&searchLocation=13526--

**Comment by iBixee** [comment]
Thank you!
