### ISSUE TITLE
The number of jobs from Hoffman don't correspond with the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#26]
ENVIROMENT: production
COMPANY: Hoffman
URL: [Hoffman peviitor.ro](https://scrapers.peviitor.ro/src/hoffman/)
Company's Career website: [Hoffman official website](https://career.hoffmann-group.com/job-offers.html?start=0&filter[volltext]=&filter[radius_search_location]=&filter[radius_search_range]=10)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Enter Hoffman in the search bar.
Click the button under the company logo.

Expected results:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/hoffman/) corresponds to the number of jobs on [Hoffman](https://career.hoffmann-group.com/job-offers.html?start=0&filter[volltext]=&filter[radius_search_location]=&filter[radius_search_range]=10) official website

Actual result:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/hoffman/) do not correspond to the number of jobs on [Hoffman](https://career.hoffmann-group.com/job-offers.html?start=0&filter[volltext]=&filter[radius_search_location]=&filter[radius_search_range]=10) official website
<img width="1099" alt="Screenshot at Nov 14 15-51-26" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/77848915-1ef2-424b-91fb-abbc8b1fd6bc">
<img width="1055" alt="Screenshot at Nov 14 15-50-14" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/ff63dcd8-4d56-47ab-baa9-bfa152f07fe9">

**Comment by cristiol** [comment]
fixed 
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/3c511b01-3d49-4277-9ccc-056be212d7e9)
