### ISSUE TITLE
Signant Health - Job numbers do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#260]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Signant Health](https://admin.peviitor.ro/jobs/Signanthealth)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "signanthealth" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job" and observe the official number of jobs on the company's official page

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
"Data Analyst II - Operations" job opening is missing from the list.

<br>

**Comment by cristiol** [comment]
![image](https://github.com/user-attachments/assets/f8851d03-1ae2-4fa6-9564-e4d3b7311432)
![image](https://github.com/user-attachments/assets/9354a305-2d5b-48df-a0e6-b87d165d9f57)

**Comment by iBixee** [comment]
Thank you!
