### ISSUE TITLE
Steelcase - Job numbers do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#261]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Steelcase](https://admin.peviitor.ro/jobs/Steelcase)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "Steelcase" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job" and observe the official number of jobs on the company's official page

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
2 job openings are missing from the list.

<br>

_**Additional information:**
[Jobs listings link](https://careers.steelcase.com/external/SearchJobs/?3_142_3=38706&folderOffset=0)_

**Comment by cristiol** [comment]
fixed
![image](https://github.com/user-attachments/assets/83557715-dd3d-4e07-83bb-2078b7fadfa2)
![image](https://github.com/user-attachments/assets/6fb41af5-7d62-495e-ad01-dba428477d45)

**Comment by iBixee** [comment]
Thank you!
