### ISSUE TITLE
Wavestone - Job numbers do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#263]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Wavestone](https://admin.peviitor.ro/jobs/Wavestone)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "Wavestone" in the search field
2) Observe the number of jobs inside the company card
3) Click on "Vizualizeaza Joburi"
4) Click on "Catre Job" and observe the official number of jobs on the company's official page

>**EXPECTED RESULTS:**
Number of jobs matches the official website.

>**ACTUAL RESULTS:**
1 job opening is missing from the list: **"Senior Consultant"**

<br>

_**Additional information:**
[Jobs listings link](https://romania-career.wavestone.com)_

**Comment by cristiol** [comment]
now it s ok
![image](https://github.com/user-attachments/assets/5afff6b2-a362-41ea-beff-2409c6bb578a)
![image](https://github.com/user-attachments/assets/da0bc581-0a9b-46c9-91b8-f9db771e4f9a)

**Comment by iBixee** [comment]
Thank you!
