### ISSUE TITLE
Analitycs section from Tenneco firm doesn't display the graphic.

### ISSUE THREAD

**Issue by LoredanaFranciuc** [peviitor-ro/Scrapers_Cristi_Olteanu#269]
ENVIROMENT:
URL: https://peviitor.ro/
****
 Desktop:
```
OS: 
Browser: Chrome
Version: Windows 10
```

 
### **STEPS TO REPRODUCE:**
1) Go to: https://admin.peviitor.ro/jobs/Teneco
2) Observe "Analitycs" section

>**EXPECTED RESULTS:**
The graphic is displayed since there are jobs available

>**ACTUAL RESULTS:**
In the Analitycs" section, the graphic is not present, and the message "_Nu exista date pentru aceasta companie in baza de date_" is displayed.
<br>

**Screenshots**
...
![2024-11-20_23h39_03](https://github.com/user-attachments/assets/e4e1c207-466f-458c-ae36-8fc956d725af)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/user-attachments/assets/b2d0f95c-d814-4498-b275-85a291f561d6)
