### ISSUE TITLE
The number of jobs from Ses don't correspond with the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#27]
ENVIROMENT: production
COMPANY: Ses
URL: [Ses peviitor.ro](https://scrapers.peviitor.ro/src/ses/)
Company's Career website: [Ses official website](https://careers.ses.com/search/?createNewAlert=false&q=&locationsearch=RO&optionsFacetsDD_customfield3=&optionsFacetsDD_customfield5=)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Enter Ses in the search bar.
Click the button under the company logo.
Click the Run scraper button.

Expected results:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/ses/) corresponds to the number of jobs on [Ses](https://careers.ses.com/search/?createNewAlert=false&q=&locationsearch=RO&optionsFacetsDD_customfield3=&optionsFacetsDD_customfield5=) official website

Actual result:
 This job does not belong to [Ses company](https://careers.ses.com/search/?createNewAlert=false&q=&locationsearch=RO&optionsFacetsDD_customfield3=&optionsFacetsDD_customfield5=) official website
<img width="1361" alt="Screenshot at Nov 16 15-09-32" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/6bae7629-715a-46ee-91b9-db7199922e4a">
<img width="997" alt="Screenshot at Nov 16 15-18-39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/a1e5c64f-8b3b-4554-908f-b9a55ffd035a">

**Comment by cristiol** [comment]
There are no more available jobs in Romania so the scraper is working well
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/5d2c4550-8567-4246-8f07-601748dae191)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/9f58f8a3-52f0-4f60-a299-c7019b40a420)
