### ISSUE TITLE
The numbers of jobs from Superbet does not correspond with the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#28]
ENVIROMENT: production
COMPANY: Superbet
URL: [Superbet peviitor.ro](https://scrapers.peviitor.ro/src/superbet/)
Company's Career website: [Superbet official website](https://boards.eu.greenhouse.io/superbet)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Enter Superbet in the search bar.
Click the button under the company's logo.
Click the button Run Scraper.

Expected results:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/superbet/) corresponds to the number of jobs on [Superbet](https://boards.eu.greenhouse.io/superbet) official website

Actual result:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/superbet/) do not correspond to the number of jobs on [Superbet](https://boards.eu.greenhouse.io/superbet) official website
<img width="1022" alt="Screenshot at Nov 17 13-06-49" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/f41723a7-0039-43bb-91cd-37e39101fee1">
<img width="669" alt="Screenshot at Nov 17 13-07-13" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/260fb8fa-3aef-416a-b81a-369764e0f779">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/8957bc68-d2dd-4952-9f76-a1563969e501)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/6f26ff7c-473b-4787-bbf6-e66728768e7e)
