### ISSUE TITLE
The numbers of jobs from Teneco does not correspond with the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#29]
ENVIROMENT: production
COMPANY: Teneco
URL: [Teneco peviitor.ro](https://scrapers.peviitor.ro/src/teneco/index.html)
Company's Career website: [Teneco official website](https://jobs.tenneco.com/search/?q=&locationsearch=Romania)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Enter Teneco in the search bar.
Click the button under the company's logo.
Click the button Run Scraper.

Expected results:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/teneco/index.html) corresponds to the number of jobs on [Teneco](https://jobs.tenneco.com/search/?q=&locationsearch=Romania) official website

Actual result:
The number of jobs on [peviitor.ro](https://scrapers.peviitor.ro/src/teneco/index.html) do not correspond to the number of jobs on [Teneco](https://jobs.tenneco.com/search/?q=&locationsearch=Romania) official website
<img width="1132" alt="Screenshot at Nov 17 16-47-57" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/346e1d24-0703-467e-88a4-0bee1e12ffbf">
<img width="1026" alt="Screenshot at Nov 17 16-48-20" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/37a774c6-38c9-4985-b5c1-ba2fe84dcb7d">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/61eea2ad-b56a-43bc-9d88-cdd34fe19444)
