### ISSUE TITLE
Error in the name of the city from Timken

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#30]
ENVIROMENT: production
COMPANY: Timken
URL: [Timken peviitor.ro](https://scrapers.peviitor.ro/src/timken/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Timken in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.

Expected result:
All jobs contain valid city names

Actual result:
Jobs do not contain valid city names
<img width="1503" alt="Screenshot at Nov 20 14-19-20" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/28140f59-fc91-43c3-99e7-b0e3e010779a">

**Comment by cristiol** [comment]
There are no more available jobs in Romania.
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/443b81c2-a949-44b8-a234-db0e14dde896)
