### ISSUE TITLE
Error in the name of the city from Hirschmann

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#32]
ENVIROMENT: production
COMPANY: Hirschmann
URL: [Hirschmann peviitor.ro](https://scrapers.peviitor.ro/src/hirschmann/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Hirschmann in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.

Expected result:
All jobs contain valid city names

Actual result:
Jobs do not contain valid city names
<img width="1404" alt="Screenshot at Nov 21 15-14-50" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/52a60f23-9bbd-403b-8601-8b9ce9d85f41">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/7ba463e7-4d8c-4fc1-8662-e17d5adb43ad)
