### ISSUE TITLE
The number of jobs from Hirschmann does not correspond with the official site

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#33]
ENVIROMENT: production
COMPANY: Hirschmann
URL: [Hirschmann peviitor.ro](https://scrapers.peviitor.ro/src/hirschmann/index.html)
Company's Career website: [Hirschmann official website](https://www.hirschmann-automotive.com/en/career/vacancies)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Enter Hirschmann in the search bar.
Click the button the company logo.

Expected results:
The number of jobs on [pe.viitor.ro](https://scrapers.peviitor.ro/src/hirschmann/index.html) corresponds to the number of jobs on [Hirschmann](https://www.hirschmann-automotive.com/en/career/vacancies) official website

Actual result:
The number of jobs on [pe.viitor.ro](https://scrapers.peviitor.ro/src/hirschmann/index.html) do not correspond to the number of jobs on [Hirschmann](https://www.hirschmann-automotive.com/en/career/vacancies) official website
<img width="957" alt="Screenshot at Nov 21 17-45-13" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/d45c8c46-81e4-4d9f-9132-3b87e32fcda4">
<img width="1201" alt="Screenshot at Nov 21 17-44-49" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/eb196e52-f381-4ba3-b672-27b564812172">

**Comment by cristiol** [comment]
acolo sunt 9 joburi si o 'cerere speculativa' si deaceea scraperul intoarce 9 joburi
