### ISSUE TITLE
Codecool - Job types do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#35]
COMPANY: Codecool
URL: [Codecool peviitor.ro](https://scrapers.peviitor.ro/src/codecool/index.html)
Company's Career website: [Codecool official website](https://codecool.bamboohr.com/careers?source=aWQ9MTA=)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/codecool/index.html) must be open in browser.

Steps:
1. Scroll down to the job listings
2. Observe the job types
3. Scroll up to the logo
4. Hover over the logo and click the "Careers" text 
5. Observe the job types for "Customer Service Specialist" and "Junior HR Recruiter"

Expected results:
Job types match the company's official website listings

Actual result:
Job types for "Customer Service Specialist" and "Junior HR Recruiter" should be listed as Hybrid as on the company's official website. *Please note that on the official website there's another job listed as "Trainer/formator pentru cursuri IT", JD is written in Romanian and the job type is Remote.

<img width="1188" alt="Screenshot 2023-11-23 at 03 05 49" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/6bb40eae-8ceb-45b2-be52-55b470af9ae2">

<img width="1135" alt="Screenshot 2023-11-23 at 03 04 32" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/facf9828-9453-4955-885a-4a4dea39fb33">

<img width="1436" alt="Screenshot 2023-11-23 at 03 02 40" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/746ac229-c320-4d5d-930c-f433dde61b7d">

**Comment by cristiol** [comment]
fixed
![Uploading image.png…]()
