### ISSUE TITLE
Colgate - Job types do not match the official website(Colgate)

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#36]
COMPANY: Colgate
URL: [Colgate peviitor.ro](https://scrapers.peviitor.ro/src/colgate/index.html)
Company's Career website: [Colgate official website](https://jobs.colgate.com/go/View-All-Jobs/8506400/?q=&q2=&alertId=&locationsearch=&title=&location=RO&department=&facility=)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/colgate/index.html) must be open in browser.

Steps:

1. Scroll down to the jobs list
2. Observe the job type for the listed jobs
3. Click on the "Vezi Postul" button 
4. Observe the job type on the official website 

Expected results:
Job types match the company's official website listings

Actual result:
Job types should be listed as Hybrid as on the company's official website. 

<img width="1195" alt="Screenshot 2023-11-23 at 03 28 05" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/d885c255-f3a5-497f-95c1-b1ed58bc747d">

<img width="1204" alt="Screenshot 2023-11-23 at 03 28 26" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/ac882681-a65a-48d9-a96e-229f82730d7d">

<img width="1206" alt="Screenshot 2023-11-23 at 03 28 42" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/81a6eeb2-f737-4396-b98a-8ae1d302a2b3">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/55121fd3-cfc2-4ff1-9930-116513752bb7)
