### ISSUE TITLE
VictorySquarePartners - Scraper Ui does not coincide with the jobs on the presentation site

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#37]
ENVIROMENT: production
COMPANY: VictorySquarePartners
URL 1: [VictorySquarePartners peviitor.ro](https://scrapers.peviitor.ro/src/victorysquarepartners/)
URL 2: [VictorySquarePartners peviitor.ro](https://peviitor.ro/rezultate?q=victorysquare&country=Rom%C3%A2nia&page=1)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter VictorySquarePartners in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.
Click the See jobs button.

Expected result:
The number of jobs on [Scraper Ui](https://scrapers.peviitor.ro/src/victorysquarepartners/) coincides with the jobs on the presentation [site](https://peviitor.ro/rezultate?q=victorysquare&country=Rom%C3%A2nia&page=1)

Actual result:
The number of jobs on [Scraper Ui](https://scrapers.peviitor.ro/src/victorysquarepartners/) does not coincide with the jobs on the presentation [site](https://peviitor.ro/rezultate?q=victorysquare&country=Rom%C3%A2nia&page=1)
<img width="1024" alt="Screenshot at Nov 23 15-14-06" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/d8545f89-42f3-4e39-8f89-01ce6e24df54">
<img width="419" alt="Screenshot at Nov 23 15-14-30" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/c8dfa6f3-20ae-4561-8278-15dfb0ca149d">

**Comment by cristiol** [comment]
fixed

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/bc8813a1-2613-4f1a-9602-a8d2a4aa16c1)
