### ISSUE TITLE
Damen - Issues related to job titles, location errors, and job types accuracy

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#38]
COMPANY: Damen
URL: [Damen peviitor.ro](https://scrapers.peviitor.ro/src/damen/index.html)
Company's Career website: [Damen official website](https://career.damen.com/jobs/?customField1=Romania&date=all&keywords=&sort=recent)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/damen/index.html) must be open in browser.

Steps:

1. Scroll down to the job listings section.
2. View job listings and details for various positions.
3. Note inconsistencies in job titles, location information, and job types.

Expected results:
The job titles, location details, and job types should accurately reflect the information provided by the official website.

Actual result:
Discrepancies are observed in job titles, location information, and job types.

<img width="1355" alt="Screenshot 2023-11-23 at 19 05 25" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/ed750e31-0f0e-4d8b-8056-262579f86b5c">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/6b294185-a2cd-46d6-aa73-77465f751392)

**Comment by iBixee** [comment]
Thank you!
