### ISSUE TITLE
Dennemeyer - Number of job listings do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#39]
COMPANY: Dennemeyer
URL: [Dennemeyer peviitor.ro](https://scrapers.peviitor.ro/src/dennemeyer/index.html)
Company's Career website: [Damen official website](https://dennemeyer.wd3.myworkdayjobs.com/en-US/dennemeyer_careers?locations=99c9060b642e1001e86635de40a00000&locations=023dd96435d8016f98adf461d036dbdb)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/dennemeyer/index.html) must be open in browser.

Steps:

1. Observe number of job listings. 
2. Observe the various positions.
3. Navigate to and click the Careers button
4. Observe number and positions of job listings on the company's official webpage

Expected results:
The job listing number should accurately reflect the information provided by the official website.

Actual result:
Discrepancies are observed in job listings.

<img width="720" alt="Screenshot 2023-11-23 at 19 49 12" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/559c6f25-9bc9-425e-964c-2a7fad889187">

<img width="890" alt="Screenshot 2023-11-23 at 19 52 07" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/838eaab6-b1cb-48e5-92ea-860802092247">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/a2bcd06f-79b4-42b9-8c72-3c05458729b3)

**Comment by iBixee** [comment]
Thank you, Cristi!
