### ISSUE TITLE
Edenred - Missing job locations on the job listing

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#41]
COMPANY: Edenred
URL: [Edenred peviitor.ro](https://scrapers.peviitor.ro/src/edenred/index.html)
Company's Career website: [Edenred official website](https://www.edenred.ro/ro/descopera-jobul-potrivit)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/edenred/index.html) must be open in browser.

Steps:

1. Scroll down to the job listings.
2. Navigate to and click the "Vezi Postul" button under the "Customer Service Representative" job post
3. Scroll down to the "OTHER DETAILS" section of the page on the company's official webpage
4. Observe locations on the company's official webpage

Expected results:
The job locations should match the information provided by the official website.

Actual result:
Discrepancies are observed in job locations.

<img width="468" alt="Screenshot 2023-11-24 at 13 50 22" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/60533494-e8ea-405d-894d-cbe1a167a38c">

<img width="736" alt="Screenshot 2023-11-24 at 13 50 32" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/69057f34-45c9-4737-ac40-a55c1514992d">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/fafc1bc7-8bfe-4e5c-b484-5cdc2c074def)

**Comment by iBixee** [comment]
Thank you!
