### ISSUE TITLE
Edurom - Job types do not match the company's official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#42]
COMPANY: Edurom
URL: [Edurom peviitor.ro](https://scrapers.peviitor.ro/src/edurom/)
Company's Career website: [Edenred official website](https://www.edurom.ro/it-jobs/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/edurom/) must be open in browser.

Steps:

1. Scroll down to the job listings.
2. Observe job types for all the listings
3. Scroll up and hover over the company's logo
4. Click the "Careers" text button 
5. Observe all job types on the company's official webpage

Expected results:
The job types should match the information provided by the official website.

Actual result:
Discrepancies are observed in job types.

<img width="1377" alt="Screenshot 2023-11-24 at 14 21 39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e1959a6f-2e2f-4a91-92ff-b8535760ce4c">

<img width="1384" alt="Screenshot 2023-11-24 at 14 22 04" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/56dbfbb2-19a8-4679-870a-efa15518103a">

**Comment by cristiol** [comment]
fixed 
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/fa7248fa-5ba4-4b66-bfb1-e4de2b8571f4)

**Comment by iBixee** [comment]
Fantastic work! Thank you!
