### ISSUE TITLE
OlxGroup - Location job field is displaying error message

### ISSUE THREAD

**Issue by AdrianSandu92** [peviitor-ro/Scrapers_Cristi_Olteanu#44]
ENVIROMENT: production
COMPANY: OLX Group
URL: https://scrapers.peviitor.ro/src/olx/index.html
Company's Career website: https://jobs.eu.lever.co/olx/
Browser: Google Chrome
Device: Laptop
OS: Windows 10

Steps to reproduce:
Open: URL: https://scrapers.peviitor.ro/src/olx/index.html
Click the button: "Run Scrapper"
Scroll down and locate the "Remote Senior Backend Engineer (Java/Kotlin)" job

Expected results:
The location should be Bucuresti / Bucharest

Actual result:
Message: "Poznań is not a city in Romania" is displayed into the location field.

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/122230734/4da0ebb2-073f-4db8-ae4d-97805c77cd9e)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/2f5a76cd-5afe-43df-ba81-4c67ec0ce483)

**Comment by AdrianSandu92** [comment]
I am pleased to inform you that the reported issue (Issue #44) has been successfully retested.
I can confirm that everything is now functioning as expected.
Thank you!
