### ISSUE TITLE
OlxGroup - Job type errors

### ISSUE THREAD

**Issue by AdrianSandu92** [peviitor-ro/Scrapers_Cristi_Olteanu#45]
ENVIROMENT: production
COMPANY: OLX Group
URL: https://scrapers.peviitor.ro/src/olx/index.html
Company's Career website: https://jobs.eu.lever.co/olx/
Browser: Google Chrome
Device: Laptop
OS: Windows 10

Steps to reproduce:
Open: URL: https://scrapers.peviitor.ro/src/olx/index.html
Click the button: "Run Scrapper"
Check the job types displayed into https://scrapers.peviitor.ro/src/olx/index.html page if corresponding with the job types displayed into the https://jobs.eu.lever.co/olx/ page or see the attached print screen located below.

Expected results:
Job types should be correctly displayed according to the Olx company job page: https://jobs.eu.lever.co/olx/
Expected job types like: "On-site, Hybrid or Remote"

Actual result:
Job types displayed into the https://scrapers.peviitor.ro/src/olx/index.html page, are not the same with the job types displayed into the Company's Career website: https://jobs.eu.lever.co/olx/

Note: Job type: "Hybrid" doesn't exist in: https://scrapers.peviitor.ro/src/olx/index.html page.

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/122230734/975f90ff-411e-408b-93e1-8ae9f9c254be)

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/ab1e8641-28a4-4c74-8ff9-5efd93c5a5b3)

**Comment by AdrianSandu92** [comment]
The reported issue (Job type errors #45) has been successfully retested.
I can confirm that everything is now functioning as expected.
Thank you!
