### ISSUE TITLE
Konecranes - Job types do not match the company's official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#47]
COMPANY: Konecranes
URL: [Konecranes peviitor.ro](https://scrapers.peviitor.ro/src/konecranes/index.html)
Company's Career website: [Konecranes official website](https://careers.konecranes.com/Konecranes/search/?createNewAlert=false&q=&locationsearch=Romania)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/konecranes/index.html) must be open in browser.

Steps:

1. **Scroll down** to the job listings.
2. **Observe** job types for all the listings
3. **Click** the "Vezi Postul" button for each job
4. **Observe** job description on the company's official job listing webpage

Expected results:
The job types should match the information provided by the official website.

Actual result:
Discrepancies are observed in job types.

<img width="1366" alt="Screenshot 2023-11-27 at 13 48 39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/888eff0a-3c9d-48fb-bc04-badf4bd72164">

<img width="1378" alt="Screenshot 2023-11-27 at 13 48 30" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/4c64b86b-b1c1-4c47-836b-eaf127501cfe">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/5cfa8cc7-1cd2-463d-a12d-3e15a5440f22)

**Comment by iBixee** [comment]
Thanks! ^_^
