### ISSUE TITLE
MarshMcLennan - Job types do not match the company's official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#49]
COMPANY: MarshMcLennan
URL: [MarshMcLennan peviitor.ro](https://scrapers.peviitor.ro/src/marshmclennan/)
Company's Career website: [MarshMcLennan official website](https://careers.marshmclennan.com/global/en/search-results?keywords=&p=ChIJw3aJlSb_sUARlLEEqJJP74Q&location=Romania)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/marshmclennan/) must be open in browser.

Steps:

1. Scroll down to the job listings.
2. Observe job types for all the listings
3. Click the "Vezi Postul" button for each job
4. Observe job description on the company's official job listing webpage

Expected results:
The job types should match the information provided by the official website.

Actual result:
Discrepancies are observed in job types.

<img width="1360" alt="Screenshot 2023-11-27 at 18 11 26" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/08454967-56b5-4717-b339-3f6e141e22c0">

<img width="1368" alt="Screenshot 2023-11-27 at 18 11 39" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e2991c5c-a34b-491b-9291-4d43096b47f0">

<img width="1371" alt="Screenshot 2023-11-27 at 18 11 53" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/57ff76d4-32d1-40d3-87af-618e247691cc">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/e2ca5cfe-5751-4433-9f8c-f9b8e872678f)

**Comment by iBixee** [comment]
Stellar job! Thank you!
