### ISSUE TITLE
Damen - Number of job listing does not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#50]
COMPANY: Damen
URL: [Damen peviitor.ro](https://scrapers.peviitor.ro/src/damen/index.html)
Company's Career website: [Damen official website](https://career.damen.com/jobs/?customField1=Romania&date=all&keywords=&sort=recent)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/damen/index.html) must be open in browser.

Steps:

1. Observe number of job listings.
2. Observe the various positions.
3. Navigate to and click the Careers button
4. Observe number and positions of job listings on the company's official webpage

Expected results:
The job listing number should accurately reflect the information provided by the official website.

Actual result:
Discrepancies are observed in job listings.

<img width="831" alt="Screenshot 2023-11-28 at 12 42 21" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/f0ff4c4b-0ee7-48a0-acc5-7181d682d9da">

<img width="849" alt="Screenshot 2023-11-28 at 12 42 32" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/f8dfc41f-e0be-40b6-b7ea-9abc9e2bf810">

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/c4c3895b-360e-4d1e-a910-05d5b1dffb10)

**Comment by iBixee** [comment]
Super! Thank you!
