### ISSUE TITLE
N-able - Number of job listings do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#52]
COMPANY: N-able
URL: [N-able peviitor.ro](https://scrapers.peviitor.ro/src/n-able/index.html)
Company's Career website: [N-able official website](https://careers.n-able.com/jobs)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/n-able/index.html) must be open in browser.

Steps:

1. **Observe** number of job listings.
2. **Navigate** to and **click** the "See Jobs" button
3. Observe number of job listings

Expected results:
The job listing number should accurately reflect the information provided by the official website.

Actual result:
Discrepancies are observed in job listing number.

<img width="805" alt="Screenshot 2023-12-04 at 15 25 24" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e6b16ff0-9754-47c8-b9db-a434a229bcf9">

<img width="817" alt="Screenshot 2023-12-04 at 15 25 49" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/5cbeb091-921e-4580-8916-b3a324e20746">

**Comment by cristiol** [comment]
It's not a bug; the additional three jobs are from another company.

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/d9673cd8-966b-402f-9583-bfd118279868)

**Comment by iBixee** [comment]
Thank you!

**Comment by iBixee** [comment]
Hi Cristi. After a long consideration and retesting, unfortunately I must reopen this issue:

COMPANY: N-able
URL: [N-able peviitor.ro](https://scrapers.peviitor.ro/src/n-able/index.html)
Company's Career website: [N-able official website](https://careers.n-able.com/jobs)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:

1. **Navigate** to the search functionality.
2. **Type** the word "N-able".
3. **Observe** the search results.

Expected results:
I expected to see consistent results related only to the "N-able" company.

Actual result:
The search results returned multiple types of results, including 3 "Antal" company search results. This inconsistency is not in line with user expectations.

Additional Information:
This issue occurs consistently, and I have been able to reproduce it reliably using the provided steps to reproduce.
So far the problem is observed on [site](https://peviitor.ro/).
The issue still persists after several test runs.

**Comment by cristiol** [comment]
First of all, it's not an issue related to the functionality of 'N-able' the scraper; instead, it's an issue related to the functionality of the search bar.

Secondly, it's not a bug because the search bar returns results associated with the searched keyword, which in certain cases happen to be exclusively job listings from a particular company, while in other cases, it might be job listings from different companies.

However, if for users who want to specifically search for jobs only from a particular company, a new feature should be implemented, and these issues should be raised in the search engine repository.
