### ISSUE TITLE
NVent - Job listings do not match the official website 

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#53]
COMPANY: NVent
URL: [NVent peviitor.ro](https://scrapers.peviitor.ro/src/nvent/)
Company's Career website: [NVent official website](https://nvent.wd5.myworkdayjobs.com/en-US/nVent/details/Operations-Supervisor_R13587?q=Romania&locations=090e2b79c4a401247bb7e70bbf105717)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/nvent/) must be open in browser.

Steps:

1. Observe the number, name, location and job types for all the job listings.
2. Navigate to and click the "Careers" button.
3. Observe the number, name, location and job types for all the job listings.

Expected results:
The job listings should accurately reflect the information provided by the official website.

Actual result:
Discrepancies are observed in job listing number.

<img width="1000" alt="Screenshot 2023-12-04 at 15 35 07" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/241b2013-df26-45ec-8e10-45f4bbbcaac8">

<img width="762" alt="Screenshot 2023-12-04 at 15 35 48" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/cb1e197e-821d-4584-8a76-16cb00fbba22">

<img width="1184" alt="Screenshot 2023-12-04 at 15 50 05" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/a89438fe-32b4-4bf4-92fd-4e3e13a147f5">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/42db0513-3b23-4193-ba48-be88967d7146)

**Comment by iBixee** [comment]
Thank you!
