### ISSUE TITLE
NN - Job type does not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#54]
COMPANY: NN
URL: [NN peviitor.ro](https://scrapers.peviitor.ro/src/nn/)
Company's Career website: [NN official website](https://nngroup.wd3.myworkdayjobs.com/en-US/WDExternal/details/Product-Owner---General-Insurance_REQ2690569?locationCountry=f2e609fe92974a55a05fc1cdc2852122)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/nn/) must be open in browser.

Steps:

1. Observe the job types for all the job listings.
2. Navigate to and click the "Careers" button.
3. Observe job types for all the job listings.

Expected results:
The job types should accurately reflect the information provided by the official website.

Actual result:
Discrepancies are observed in job listing number.

<img width="918" alt="Screenshot 2023-12-04 at 15 55 43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/00be42e5-7f67-40e8-a18f-8fbf6d478669">

<img width="1075" alt="Screenshot 2023-12-04 at 16 00 50" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/11561271-1277-4c4a-922b-9c474151afd1">

**Comment by cristiol** [comment]
fixed

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/c165243c-2959-42eb-aad3-e8b3c9f92226)

**Comment by iBixee** [comment]
Thank you!
