### ISSUE TITLE
Levis - Logo has a checkered background

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#58]
ENVIROMENT: production
COMPANY: Levis
URL: [Levis peviitor.ro](https://scrapers.peviitor.ro/src/levis/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/levis/) must be open in browser.

Steps:

1. Observe the company's logo

Expected result:
The logo image has a clean background without any checkered pattern.

Actual result:
The company's logo has a checkered background.

<img width="266" alt="Screenshot 2023-11-29 at 12 37 35" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/8c5487e0-c13d-4866-be44-89c9cee2e974">

**Comment by cristiol** [comment]
done
@lalalaurentiu

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/c5a45f7c-8b01-4601-9886-31036f779556)
