### ISSUE TITLE
MassMutual - Logo has a checkered background

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#59]
ENVIROMENT: production
COMPANY: MassMutual
URL: [MassMutual peviitor.ro](https://scrapers.peviitor.ro/src/massmutual/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/massmutual/) must be open in browser.

Steps:

1. Observe the company's logo

Expected result:
The logo image has a clean background without any checkered pattern.

Actual result:
The company's logo has a checkered background.

<img width="274" alt="Screenshot 2023-11-29 at 12 41 41" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/05d52170-00ae-4929-aa48-7ceb8677af98">

**Comment by lalalaurentiu** [comment]
@cristiol change logo url from scraper

**Comment by cristiol** [comment]
@lalalaurentiu done I changed the url logo

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/f95e5be6-c136-4b8e-a450-bcf0b710a11f)

**Comment by iBixee** [comment]
Thank you!
