### ISSUE TITLE
Pearson - Job types do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#61]
COMPANY: Pearson
URL: [Pearson peviitor.ro](https://scrapers.peviitor.ro/src/pearson/)
Company's Career website: [Pearson official website](https://pearson.jobs/jobs/?location=Romania&r=25)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/pearson/) must be open in browser.

Steps:

1. **Scroll** down and **observe** the job types.
2. **Navigate** to and **click** the "Careers" button.
3. **Observe** job types.

Expected results:
The job types should accurately reflect the information provided by the official website.

Actual result:
Differences are observed in job types.

<img width="835" alt="Screenshot 2023-12-05 at 14 48 01" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/8adffc9c-1db3-41be-9e5e-ec7699156c9c">

<img width="718" alt="Screenshot 2023-12-05 at 14 52 04" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e4009e33-ed7f-4eb4-8a68-e74e74fb77af">

**Comment by cristiol** [comment]
I don't think it's a bug because it's specified as hybrid only where possible, and since the job location is 'Romania( and not a specific city)' the job type is by default remote
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/4018c711-1456-431b-b7ad-1525e57bfd2c)

**Comment by iBixee** [comment]
I understand but for these two particular job listings on our webpage the job type is listed as "on-site" and on their official website one if flexible and the other one is hybrid or remote.

<img width="990" alt="Screenshot 2023-12-06 at 13 30 43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/7732de2c-766f-4f4f-9b80-0b814fe5e45a">

<img width="835" alt="Screenshot 2023-12-05 at 14 48 01" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/c1cbcb58-1402-4b1c-a845-d94bc27158a5">

<img width="718" alt="Screenshot 2023-12-05 at 14 52 04" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/ad051e67-dc7e-4e12-8f81-9f33946f1644">

**Comment by iBixee** [comment]
It actually looks good now. Thank you!
