### ISSUE TITLE
Picsart - Job types do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#62]
COMPANY: Picsart
URL: [Picsart peviitor.ro](https://scrapers.peviitor.ro/src/picsart/)
Company's Career website: [Picsart official website](https://picsart.com/jobs/vacancies/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/picsart/) must be open in browser.

Steps:

1. Scroll down and observe the job types.
2. Navigate to and click the "Careers" button.
3. Observe job types.

Expected results:
The job types should accurately reflect the information provided by the official website.

Actual result:
Differences are observed in both job types.

<img width="793" alt="Screenshot 2023-12-05 at 15 46 30" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/7383d8f1-d339-4b7c-bedb-9bac4f85e351">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/60ff321f-339a-4c31-8c69-65a4489b74c3)

**Comment by iBixee** [comment]
Thanks!
