### ISSUE TITLE
P&G - Error 404 page not found

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#63]
ENVIROMENT: production
COMPANY: P&G
URL: [P&G scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/P&G/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter P&G in the search bar.
3. Click the button under the company's logo.

Expected result:
The Scraper-UI related to the company opens.

Actual result:
Error 404 "Page Not Found"
<img width="424" alt="Screenshot at Dec 06 14-45-02" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/d0104819-468e-4b01-b0fc-d8e0e138f747">
<img width="1105" alt="Screenshot at Dec 06 14-45-20" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/8cd7c8a1-c561-4d40-9fd5-22323b8b166c">

**Comment by cristiol** [comment]
I changed the name
@lalalaurentiu

**Comment by lalalaurentiu** [comment]
@AdelinaGuliman this is new [url](https://scrapers.peviitor.ro/src/proctorandgamble/index.html)

**Comment by AdelinaGuliman** [comment]
ok. case closed
