### ISSUE TITLE
Salesconsulting - Error in the city names

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#66]
ENVIROMENT: production
COMPANY: Salesconsulting
URL: [Salesconsulting scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/salesconsulting/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Salesconsulting in the search bar.
3. Click the button under the company's logo.
4. Click on the Run Scraper button.

Expected result:
All jobs contain valid city names

Actual result:
All jobs does not contain valid city names.

<img width="1049" alt="Screenshot at Dec 07 15-51-15" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/1c0f2152-0d85-4183-b6aa-0fda9e73096a">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/9bcabd80-f462-4bd5-b5de-e344eb1a0d20)
