### ISSUE TITLE
Steelcase - Job types do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#68]
COMPANY: Steelcase
URL: [Steelcase peviitor.ro](https://scrapers.peviitor.ro/src/steelcase/index.html)
Company's Career website: [Steelcase official website](https://careers.steelcase.com/external/SearchJobs/?3_142_3=38706&folderOffset=0)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/steelcase/index.html) must be open in browser.

Steps:

1. **Scroll** down and **observe** all the job types.
2. **Navigate** to and **click** the "Careers" button.
3. **Observe** all job types.

Expected results:
The job types should accurately reflect the information provided by the official website.

Actual result:
Differences are observed in most job types.

<img width="637" alt="Screenshot 2023-12-07 at 18 43 47" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/3698eb4e-9a26-4be2-9286-9ddad128fe5b">

<img width="680" alt="Screenshot 2023-12-07 at 18 43 04" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e229d233-eb5d-4507-ad61-cf927fd7a326">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/dd320a30-0989-4fab-b0eb-3d6eae5963d1)

**Comment by iBixee** [comment]
Thank you!
