### ISSUE TITLE
The number of jobs on Dennemeyer does not correspond to the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#7]
ENVIROMENT: production
COMPANY: Dennemeyer. 
URL: [Dennemeyer peviitor.ro](https://peviitor.ro/rezultate?q=dennemeyer&country=Rom%C3%A2nia&page=1) 
Company's Career website: [Dennemeyer official website](https://dennemeyer.wd3.myworkdayjobs.com/dennemeyer_careers?locations=99c9060b642e1001e86635de40a00000)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:

The [site](https://peviitor.ro/) must be open in browser.

Steps:

Enter Dennemeyer in the search bar.

Click the button the company logo.

Expected results:

The number of jobs on [pe.viitor.ro](http://www.peviitor.ro/) corresponds to the number of jobs on [Dennemeyer](https://dennemeyer.wd3.myworkdayjobs.com/dennemeyer_careers?locations=99c9060b642e1001e86635de40a00000) official website 

Actual result:

The number of jobs on [pe.viitor.ro](http://www.peviitor.ro/) do not correspond to the number of jobs on [Dennemeyer](https://dennemeyer.wd3.myworkdayjobs.com/dennemeyer_careers?locations=99c9060b642e1001e86635de40a00000) official website
<img width="1250" alt="Dennemeyer" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/da916d1b-2ebf-42bc-a3c8-4f21ff8f4e24">
<img width="1034" alt="Dennemeyer 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/293f6098-f5a7-4adb-8cf0-85870b72b867">

**Comment by cristiol** [comment]
fixed

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/e2bb028d-745d-46c4-987d-30d06110dc49)
