### ISSUE TITLE
Snyk - Job types and locations do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#70]
COMPANY: Snyk
URL: [Snyk peviitor.ro](https://scrapers.peviitor.ro/src/snyk/)
Company's Career website: [Snyk official website](https://boards.greenhouse.io/snyk?gh_src=3f9b65652us)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/snyk/) must be open in browser.

Steps:

1. **Scroll** down and **observe** all the job types and locations.
2. **Navigate** to and **click** the "Careers" button.
3. **Observe** all job types and locations.

Expected results:
Job types and locations should accurately reflect the information provided by the official website.

Actual result:
Differences are observed in most job types and locations.

<img width="682" alt="Screenshot 2023-12-08 at 17 28 15" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/65a00e49-3e3b-4e13-a178-4d229e9bb614">

<img width="952" alt="Screenshot 2023-12-08 at 17 21 45" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/0354e88c-aa7c-4b46-b65c-6ce261b46456">

<img width="631" alt="Screenshot 2023-12-08 at 17 32 44" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/fa250fe5-5271-4e07-bec9-598cf20f8be0">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/5645c741-f512-4994-9839-aed49a6c3f29)

**Comment by iBixee** [comment]
Thank you!
