### ISSUE TITLE
Adecco - Error in the city names

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#72]
ENVIROMENT: production
COMPANY: Adecco
URL: [Adecco scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/adecco/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Adecco in the search bar.
3. Click the button under the company's logo.
4. Click on the Run Scraper button.

Expected result:
All jobs contain valid city names

Actual result:
All jobs does not contain valid city names.

<img width="723" alt="Screenshot at Dec 13 13-18-24" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/6ddcf0e8-dfa0-40e4-9ce9-f61f035a922c">
<img width="996" alt="Screenshot at Dec 13 13-18-37" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/866a4750-1814-48f3-9e41-9d850f790f5b">
<img width="844" alt="Screenshot at Dec 13 13-18-49" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/6edeec61-fd0f-478f-beb2-a6d418e05e15">
<img width="691" alt="Screenshot at Dec 13 13-19-02" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/b78e21b8-acfa-46d3-b691-07e9a8fb2427">
<img width="750" alt="Screenshot at Dec 13 13-19-13" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/0c08ae81-424b-44a4-81c6-4e64c591ccfe">
<img width="1489" alt="Screenshot at Dec 13 13-19-29" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/8b323a35-6746-433f-a2dd-69a828b3447e">
<img width="658" alt="Screenshot at Dec 13 13-19-45" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/ce37dc54-e8f5-4ef8-b085-9c4229ccdb95">
<img width="633" alt="Screenshot at Dec 13 13-19-57" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/1436d6c4-8d55-4b0e-9abf-07148f2958be">
<img width="632" alt="Screenshot at Dec 13 13-20-08" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/dc131e2e-1e97-4538-97d1-8d4e4a2bcd2d">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/59861b79-28dc-4892-9e01-a9e0812c3702)
