### ISSUE TITLE
Alpa - The jobs from Scraper-UI does not correspond with the company's official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#75]
ENVIROMENT: production
COMPANY: Alpla
URL: [Alpla Scraper-UI](https://scrapers.peviitor.ro/src/alpla/index.html)
Company's Career website: [Alpla official website](https://career.alpla.com/en/jobs?page=)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
1. Enter Alpla in the search bar.
2. Click the button below the company logo.
3. Click the button Run Scraper.

Expected results:
The number of jobs on [Scraper-UI](https://scrapers.peviitor.ro/src/alpla/index.html) corresponds to the number of jobs on [Alpla](https://career.alpla.com/en/jobs?page=) official website

Actual result:
The number of jobs on [Scraper-UI](https://scrapers.peviitor.ro/src/alpla/index.html) does not corresponds to the number of jobs on [Alpla](https://career.alpla.com/en/jobs?page=) official website

<img width="587" alt="Screenshot at Dec 13 14-19-27" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/15fc1ee5-9d2e-4ada-bce9-058da699c6a4">
<img width="449" alt="Screenshot at Dec 13 14-19-43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/334b7d07-2c25-4c56-866d-20535c84548e">

**Comment by cristiol** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/26b71804-addb-44d8-b885-3a667bdfdcc8)

**Comment by cristiol** [comment]
please retest
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/63a10b09-ff9d-44a8-8510-5cf6419af289)
