### ISSUE TITLE
Ascom - Invalid city name

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#78]
ENVIROMENT: production
COMPANY: Ascom
URL: [Ascom scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/ascom/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Ascom in the search bar.
Click the button under the company's logo.
Click on the Run Scraper button.

Expected result:
All jobs contain valid city names

Actual result:
All jobs does not contain valid city names.

<img width="732" alt="Screenshot at Dec 13 15-14-03" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/11a2d8aa-83cc-4bb1-b490-927b83d7a2e7">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/92ae09f1-81bf-4727-b14c-3b1df16c909d)
