### ISSUE TITLE
Siena - Job types do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers_Cristi_Olteanu#79]
COMPANY: Siena
URL: [Siena peviitor.ro](https://scrapers.peviitor.ro/src/siena/index.html)
Company's Career website: [Siena official website](https://jobs.ashbyhq.com/siena)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/siena/index.html) must be open in browser.

Steps:

1. Scroll down and observe the job types.
2. Navigate to and click the "Careers" button.
3. Observe job types.

Expected results:
The job types should accurately reflect the information provided by the official website.

Actual result:
Differences are observed in job types.

<img width="1138" alt="Screenshot 2023-12-14 at 15 32 53" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/8ee59cfb-e562-4f48-afe5-3d84cf11119b">

<img width="803" alt="Screenshot 2023-12-14 at 15 32 32" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/38e7bc4e-547d-4a41-b97e-a87927b5befe">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/f525ff5a-c3d9-44f7-8524-9d6169da3f5d)

**Comment by iBixee** [comment]
Thank you!
