### ISSUE TITLE
Astormueller - The jobs from Scraper-UI does not correspond with the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#80]
ENVIROMENT: production
COMPANY: Astormueller
URL: [Astormueller Scraper-UI](https://scrapers.peviitor.ro/src/astormueller/)
Company's Career website: [Astormueller official website](https://astormueller-ag.jobs.personio.com/?filters=eyJvZmZpY2VfaWQiOlsxMTEzNzYzLDE3NDAyMDJdfQ==)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
1.Enter Astormueller in the search bar.
2. Click the button the company logo.
3. Click the "Run Scraper" button

Expected results:
The number of jobs on [Scraper-UI](https://scrapers.peviitor.ro/src/astormueller/) corresponds to the number of jobs on [Astormueller](https://astormueller-ag.jobs.personio.com/?filters=eyJvZmZpY2VfaWQiOlsxMTEzNzYzLDE3NDAyMDJdfQ==) official website

Actual result:
The number of jobs on [Scraper-UI](https://scrapers.peviitor.ro/src/astormueller/) does not correspond to the number of jobs on [Astormueller](https://astormueller-ag.jobs.personio.com/?filters=eyJvZmZpY2VfaWQiOlsxMTEzNzYzLDE3NDAyMDJdfQ==) official website

<img width="506" alt="Screenshot at Dec 14 15-41-29" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/42a442c8-b1d8-4c15-a5b7-284d55796fa4">
<img width="685" alt="Screenshot at Dec 14 15-41-13" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/201099d3-0ab5-4456-9626-a9610375186f">

**Comment by cristiol** [comment]
On the company website, there are 12 jobs in total. Jobs for Romania are 9, 2 for Germany, and 1 for India.
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/4bbdfcad-09b3-4fb6-ae34-b214c66eaf95)
