### ISSUE TITLE
BayWa-re - Scraper-UI Error 404 

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#81]
ENVIROMENT: production
COMPANY: BayWa-re
URL: [BayWa-re peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter BayWa-re in the search bar.
Click the button under the company's logo.

Expected result:
The Scraper-UI related to the company opens.

Actual result:
Error 404 "Page Not Found"

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/8fc8d8be-1a48-4442-89d8-f5f81f760b85

**Comment by lalalaurentiu** [comment]
@cristiol change company name from baywa to bayware and baywa_scraper.py file to bayware_scraper.py to work

**Comment by cristiol** [comment]
now is working
