### ISSUE TITLE
Consensys - 2 Unavailable jobs are shown in ScrapersUI & peviitor

### ISSUE THREAD

**Issue by StroescuDiana** [peviitor-ro/Scrapers_Cristi_Olteanu#84]
ENVIROMENT: production
URL: [peviitor](https://peviitor.ro/) & [ScrapersUI](https://scrapers.peviitor.ro/src/consensys/)
**Company_careers_url**: [**Consensys**](https://consensys.io/open-roles?location=83558)
Browser: Chrome
Device: laptop
OS: MacOS

### **STEPS TO REPRODUCE:**
1) Open URL in browser
2) Type the name of the company in the search bar
3) Click on the button "Cauta"
4) Compare the jobs extracted by ScrapersUI(14) and the jobs from the comapny's website(12).
<br>

>**EXPECTED RESULTS:**
The number of jobs should be the same on both peviitor and Consensys.

>**ACTUAL RESULTS:**
The number of jobs posted on the company's website is 12 and the number of jobs returned by ScrapersUI is 14.
<br>

### Here are the 2 unavailable jobs:
<img width="450" alt="Screenshot 2023-12-15 at 10 15 15" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/129664856/a29d1624-bd14-4544-aac9-ad0ce00ea701">
<img width="450" alt="Screenshot 2023-12-15 at 10 15 34" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/129664856/d8703d04-253a-45b9-b751-7d98617eed57">

**Comment by cristiol** [comment]
First and foremost, all jobs are available.
Secondly, the residents of Romania can apply for 14 jobs, of which 12 are listed as EMEA remote, and 2 are listed as Global remote

**Comment by StroescuDiana** [comment]
@cristiol Da, asa e.
