### ISSUE TITLE
Consensys - How do you know the exact place for the romanian jobs?

### ISSUE THREAD

**Issue by StroescuDiana** [peviitor-ro/Scrapers_Cristi_Olteanu#85]
Salut @cristiol!

M-am uitat peste descrierile locurilor de munca de la firma Consensys, dar nu vad sa precizeze exact Cluj-Napoca. 
Doar precizeaza ca e remote, EMEA.
<br>

<img width="450" alt="Screenshot 2023-12-15 at 10 15 15" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/129664856/c413d0bc-8f04-40a0-a1ec-d54d1e3b878a">

<p>
<br>

<img width="135" alt="Screenshot 2023-12-15 at 10 34 21" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/129664856/4e451e6c-f597-41b5-b2fd-6750144fa3c0">

**Comment by cristiol** [comment]
In the event that the company specifies that the job is remote and residents of Romania can apply, the default city listed is the city where the company is registered in Romania.

**Comment by StroescuDiana** [comment]
Alright.
