### ISSUE TITLE
Extia - The job titles do not correspond to the company's ones

### ISSUE THREAD

**Issue by StroescuDiana** [peviitor-ro/Scrapers_Cristi_Olteanu#86]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: [**Extia**](https://www.extia-group.com/fr-en/join-us?page=1&locations=103)
Browser: Chrome
Device: laptop
OS: MacOS

### **STEPS TO REPRODUCE:**
1) Open URL in browser
2) Type the name of the company in the search bar
3) Click on the button "Cauta"
4) Check the job title for each job.
<br>

>**EXPECTED RESULTS:**
The Extia's job titles on ScrapersUI & peviitor should be the same as the ones posted on the company's website.

>**ACTUAL RESULTS:**
The "M/W" is missing from each job title.
<br>

### Extia's jobs on ScrapersUI
<img width="1364" alt="Screenshot 2023-12-15 at 10 44 34" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/129664856/8bb89b7c-4c81-4136-964c-c45dba7f8e69">

### Extia's jobs on company's website
<img width="1162" alt="Screenshot 2023-12-15 at 10 48 08" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/129664856/b7c6820b-e569-439f-b406-6cfb8c6db89a">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/d8b43fca-6f8e-4cb3-ae0b-817599725b6a)

**Comment by StroescuDiana** [comment]
@cristiol Thank you :)
