### ISSUE TITLE
Error in the names of the cities

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#9]
ENVIROMENT: production
COMPANY: Ecolab
URL: [Ecolab peviitor.ro](https://peviitor.ro/rezultate?q=dennemeyer&country=Rom%C3%A2nia&page=1)
Company's Career website: [Ecolab official website](https://jobs.ecolab.com/job-search-results/?location=Rom%C3%A2nia&country=RO&radius=25)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Ecolab in the search bar.
3. Click the button under the company's logo.
4. Click the Run Scraper button.

Expected result:
1. All jobs contain valid city names

Actual result:
1. Jobs do not contain valid city names
<img width="1460" alt="ecolab" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/1f9ac890-20e3-4968-b137-4784d41aa433">
<img width="1288" alt="ecolab 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/1cb34c7f-f8b7-4794-bfe7-ca82d7e89a7d">

**Comment by cristiol** [comment]
fixed 
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/d5824422-a93d-47c2-afef-60ced530cdc3)
