### ISSUE TITLE
Adeco - Invalid city names

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#93]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/adecco/index.html)
**Company_careers_url**: [Adecco](https://www.adecco.ro/jobs/?page=0)
 Desktop:
```
OS: IOS
Browser: Google Chrome
Version: 98.0.4758.102
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Adecco in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
All jobs contain valid city names

>**ACTUAL RESULTS:**
There are jobs does not contain valid city names

<br>

**Screenshots**
<img width="660" alt="Screenshot at Jan 09 13-51-43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/6b21f767-2f4f-4867-9b40-fddf63b21fbb">
<img width="612" alt="Screenshot at Jan 09 13-51-59" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/f1d64339-8a9d-47fe-a3e9-bdacf59c7cbd">
<img width="575" alt="Screenshot at Jan 09 13-52-43" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/b2b85a36-7c7f-4bc8-b7f5-43721f464d30">

**Comment by cristiol** [comment]
fixed
