### ISSUE TITLE
Antal - Inavid city name

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#94]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/antal/index.html)
**Company_careers_url**: [Antal](https://www.antal.com/jobs?keywords=%C2%A7or=&location=1721&type=&page=)
 Desktop:
```
OS: IOS
Browser: Google Chrome
Version: 98.0.4758.102
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Antal in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
All jobs contain valid city names

>**ACTUAL RESULTS:**
There are jobs does not contain valid city names

<br>

**Screenshots**
<img width="406" alt="Screenshot at Jan 10 13-20-58" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/164d2fbf-bf2b-4bca-8a45-85215b12a74e">
<img width="523" alt="Screenshot at Jan 19 15-20-33" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/be7bd9a3-09d3-48cc-9556-585e4e56c192">

**Comment by cristiol** [comment]
fixed
