### ISSUE TITLE
AMS - The number of jobs does not correspond to the one on the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#95]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/ams/index.html)
**Company_careers_url**: [AMS](https://www.careers-page.com/ams-hr)
 Desktop:
```
OS: IOS
Browser: Google Chrome
Version: 98.0.4758.102
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter AMS in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/ams/index.html) corresponds to the number of jobs from the [AMS](https://www.careers-page.com/ams-hr) official website

>**ACTUAL RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/ams/index.html) does not correspond to the number of jobs from the [AMS](https://www.careers-page.com/ams-hr) official website

<br>

**Screenshots**
<img width="400" alt="Screenshot at Jan 11 14-18-02" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/a3324657-0c29-4b2f-8e61-7dc2f52726c8">
<img width="527" alt="Screenshot at Jan 11 14-18-31" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/3646b499-8769-4d1f-8a93-e7d162ea1107">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/cf754deb-fba7-4be5-ab21-dc25cb078e3a)
