### ISSUE TITLE
Caseware - Invalid city names

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#96]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/antal/index.html)
**Company_careers_url**: [Caseware](https://jobs.lever.co/caseware?location=Cluj%2C%20Romania)
 Desktop:
```
OS: MacOS
Browser: Mozilla Firefox
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Caseware in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
All jobs contain valid city names

>**ACTUAL RESULTS:**
There are jobs does not contain valid city names

<br>

**Screenshots**
<img width="1413" alt="Screenshot at Jan 12 13-16-17" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/45ac9d32-1886-4b2f-8116-912c26dee35a">

**Comment by cristiol** [comment]
fixed

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/8deb72d0-61d5-4564-aba1-cd28730a3c0b)
