### ISSUE TITLE
Edurom - Invalid city names

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#97]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/edurom/index.html)
**Company_careers_url**: [Edurom](https://www.edurom.ro/it-jobs/)
 Desktop:
```
OS: MacOS
Browser: Mozilla Firefox
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Edurom in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
All jobs contain valid city names

>**ACTUAL RESULTS:**
There are jobs does not contain valid city names

<br>

**Screenshots**
<img width="532" alt="Screenshot at Jan 12 15-41-13" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/50778116-c1ef-429c-a799-a66525b2d208">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/b3cea38f-3811-4423-b5e1-bdb25a5540ba)
