### ISSUE TITLE
Expressvpn - The number of jobs does not correspond to the one on the official

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#98]
ENVIROMENT: production
URL: [Scrapers.peviitor](https://scrapers.peviitor.ro/src/expressvpn/index.html)
**Company_careers_url**: [Expressvpn](https://www.expressvpn.com/jobs/job-openings)
 Desktop:
```
OS: IOS
Browser: Mozilla Firefox
```

 
### **STEPS TO REPRODUCE:**
1) Click on Firme from footer.
2) Enter Expressvpn in the search bar
3) Click the button under the company's logo.
4) The company-specific scraper page opens.
5) Click "Run Scraper" button

>**EXPECTED RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/expressvpn/index.html) corresponds to the number of jobs from the [AMS](https://www.expressvpn.com/jobs/job-openings) official website

>**ACTUAL RESULTS:**
The number of jobs from [scrapers.peviitor](https://scrapers.peviitor.ro/src/expressvpn/index.html) does not correspond to the number of jobs from the [AMS](https://www.expressvpn.com/jobs/job-openings) official website

<br>

**Screenshots**
<img width="295" alt="Screenshot at Jan 12 15-52-18" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/c76627e7-3b9f-4de2-ada4-b5454c62c236">
<img width="460" alt="Screenshot at Jan 12 15-52-46" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/21857b72-0b4d-474a-8847-47b9bcf7fa2c">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/af7e59f1-3acf-40a2-9b05-1cbe1151dd91)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/7f57d951-fc7d-459e-b877-67194b883d88)
